// 문법 카드 데이터 — cat: 분류, q: 문제(___이 빈칸), c: 보기, a: 정답, why: 해설
const GRAMMAR = [
  // ===== 시제 =====
  { cat: "시제", q: "She ___ to the gym every morning.", c: ["go", "goes", "going", "gone"], a: "goes", why: "주어가 3인칭 단수(She)이고 반복되는 습관이므로 현재시제 goes를 써요." },
  { cat: "시제", q: "I ___ dinner when you called.", c: ["cook", "cooked", "was cooking", "am cooking"], a: "was cooking", why: "전화가 온 '그 순간에 하고 있던 일'이므로 과거진행형을 써요." },
  { cat: "시제", q: "We ___ each other since 2019.", c: ["know", "knew", "have known", "are knowing"], a: "have known", why: "since(~이래로)와 함께 과거부터 지금까지 이어지는 일은 현재완료를 써요." },
  { cat: "시제", q: "Look at those clouds. It ___ rain soon.", c: ["will", "is going to", "would", "was going to"], a: "is going to", why: "눈앞의 근거(구름)를 보고 하는 예측은 be going to가 자연스러워요." },
  { cat: "시제", q: "The train ___ when we got to the station.", c: ["already leaves", "has already left", "had already left", "already left"], a: "had already left", why: "역에 도착한 것(과거)보다 더 이전에 일어난 일은 과거완료(had + p.p.)를 써요." },
  { cat: "시제", q: "I ___ my homework yet.", c: ["don't finish", "didn't finish", "haven't finished", "hadn't finished"], a: "haven't finished", why: "yet(아직)은 보통 현재완료 부정문과 함께 써요." },
  { cat: "시제", q: "This time tomorrow, I ___ on a beach.", c: ["lie", "will be lying", "lay", "have lain"], a: "will be lying", why: "미래의 특정 시점에 진행 중일 일은 미래진행형(will be -ing)을 써요." },
  { cat: "시제", q: "Water ___ at 100 degrees.", c: ["boil", "boils", "boiled", "is boiling"], a: "boils", why: "변하지 않는 일반적 사실은 항상 현재시제로 표현해요." },
  // ===== 전치사 =====
  { cat: "전치사", q: "The meeting is ___ Monday.", c: ["in", "on", "at", "by"], a: "on", why: "요일 앞에는 on을 써요. (in + 월/연도, at + 시각)" },
  { cat: "전치사", q: "I'll see you ___ noon.", c: ["in", "on", "at", "by"], a: "at", why: "구체적인 시각(noon, 7 o'clock 등) 앞에는 at을 써요." },
  { cat: "전치사", q: "She's been working here ___ 2020.", c: ["for", "since", "during", "from"], a: "since", why: "since + 시작 시점, for + 기간. 2020은 시점이므로 since예요." },
  { cat: "전치사", q: "We walked home ___ the rain.", c: ["in", "on", "at", "under"], a: "in", why: "'빗속에서'는 in the rain이라고 표현해요." },
  { cat: "전치사", q: "The cafe is ___ the bank and the pharmacy.", c: ["among", "between", "beside", "along"], a: "between", why: "둘 사이는 between, 셋 이상 사이는 among을 써요." },
  { cat: "전치사", q: "He's really good ___ cooking.", c: ["in", "at", "on", "with"], a: "at", why: "be good at(~을 잘하다)은 통째로 외워두면 좋은 표현이에요." },
  { cat: "전치사", q: "I'm looking forward ___ seeing you.", c: ["to", "for", "at", "of"], a: "to", why: "look forward to에서 to는 전치사라 뒤에 -ing가 와요." },
  { cat: "전치사", q: "The report is due ___ Friday.", c: ["until", "by", "on", "in"], a: "by", why: "by는 '늦어도 ~까지 (완료)', until은 '~까지 계속'이에요." },
  // ===== 관사 · 명사 =====
  { cat: "관사·명사", q: "I saw ___ interesting movie last night.", c: ["a", "an", "the", "관사 없음"], a: "an", why: "interesting은 모음 소리로 시작하므로 an을 써요." },
  { cat: "관사·명사", q: "Can you pass me ___ salt?", c: ["a", "an", "the", "관사 없음"], a: "the", why: "말하는 사람과 듣는 사람이 모두 아는 '그 소금'이므로 the를 써요." },
  { cat: "관사·명사", q: "She plays ___ piano very well.", c: ["a", "an", "the", "관사 없음"], a: "the", why: "악기를 연주할 때는 the + 악기 이름을 써요. (play the piano)" },
  { cat: "관사·명사", q: "I go to work ___ bus.", c: ["by a", "by the", "by", "on a"], a: "by", why: "by + 교통수단(bus, subway, car)에는 관사를 붙이지 않아요." },
  { cat: "관사·명사", q: "We had ___ lunch together.", c: ["a", "an", "the", "관사 없음"], a: "관사 없음", why: "식사 이름(breakfast, lunch, dinner) 앞에는 보통 관사를 안 써요." },
  { cat: "관사·명사", q: "There are three ___ on the desk.", c: ["book", "books", "a book", "the book"], a: "books", why: "셋(three)이므로 복수형 books를 써야 해요." },
  { cat: "관사·명사", q: "I need some ___ about the schedule.", c: ["informations", "information", "an information", "the informations"], a: "information", why: "information은 셀 수 없는 명사라 복수형이나 an을 쓸 수 없어요." },
  { cat: "관사·명사", q: "He gave me a piece of ___.", c: ["advices", "advice", "an advice", "the advices"], a: "advice", why: "advice도 셀 수 없는 명사예요. 셀 때는 a piece of advice처럼 써요." },
  // ===== 조동사 =====
  { cat: "조동사", q: "You ___ wear a seatbelt. It's the law.", c: ["can", "must", "might", "would"], a: "must", why: "법으로 정해진 강한 의무는 must를 써요." },
  { cat: "조동사", q: "___ you help me with this box, please?", c: ["Could", "Must", "Should", "May"], a: "Could", why: "정중한 부탁은 Could you ~?가 가장 자연스러워요." },
  { cat: "조동사", q: "You ___ eat so late. It's bad for you.", c: ["shouldn't", "can't", "mustn't", "won't"], a: "shouldn't", why: "'~하지 않는 게 좋아'라는 충고는 shouldn't를 써요." },
  { cat: "조동사", q: "She ___ speak three languages.", c: ["can", "must", "should", "may"], a: "can", why: "능력(~할 수 있다)을 나타낼 때는 can을 써요." },
  { cat: "조동사", q: "It ___ rain later. Take an umbrella.", c: ["might", "must", "should", "can't"], a: "might", why: "확실하지 않은 추측(~일지도 몰라)은 might를 써요." },
  { cat: "조동사", q: "You ___ be tired after such a long flight.", c: ["must", "can", "might not", "shouldn't"], a: "must", why: "'분명 ~일 거야'라는 강한 추측도 must로 표현해요." },
  { cat: "조동사", q: "I ___ swim when I was five.", c: ["could", "can", "must", "should"], a: "could", why: "과거의 능력은 can의 과거형 could를 써요." },
  { cat: "조동사", q: "You ___ pay now. You can pay later.", c: ["don't have to", "must not", "can't", "shouldn't"], a: "don't have to", why: "don't have to는 '~할 필요 없다', must not은 '~하면 안 된다'예요." },
  // ===== 비교 =====
  { cat: "비교", q: "This bag is ___ than that one.", c: ["cheap", "cheaper", "cheapest", "more cheap"], a: "cheaper", why: "than과 함께 둘을 비교할 때는 비교급(-er)을 써요." },
  { cat: "비교", q: "Today is ___ day of the year.", c: ["hot", "hotter", "the hottest", "most hot"], a: "the hottest", why: "'가장 ~한'은 the + 최상급으로 표현해요." },
  { cat: "비교", q: "The movie is ___ interesting than the book.", c: ["less", "least", "little", "fewer"], a: "less", why: "'덜 ~한'은 less + 형용사로 표현해요." },
  { cat: "비교", q: "She speaks English ___ than me.", c: ["good", "well", "better", "best"], a: "better", why: "well(잘)의 비교급은 better예요." },
  { cat: "비교", q: "The test was ___ easier than I expected.", c: ["very", "much", "more", "most"], a: "much", why: "비교급을 강조할 때는 very가 아니라 much(훨씬)를 써요." },
  { cat: "비교", q: "This room is twice ___ large as mine.", c: ["as", "so", "more", "than"], a: "as", why: "배수 표현은 'twice as ~ as(두 배 ~한)' 형태로 써요." },
  { cat: "비교", q: "The ___ you practice, the better you get.", c: ["much", "more", "most", "many"], a: "more", why: "'~할수록 더 ~하다'는 the 비교급, the 비교급 구문이에요." },
  { cat: "비교", q: "He is as ___ as his brother.", c: ["taller", "tallest", "tall", "more tall"], a: "tall", why: "as ~ as(~만큼 ~한) 사이에는 원급(기본형)을 써요." },
  // ===== 접속사 · 관계사 =====
  { cat: "접속사·관계사", q: "I stayed home ___ it was raining.", c: ["because", "so", "but", "although"], a: "because", why: "뒤에 이유가 오므로 because(~때문에)를 써요." },
  { cat: "접속사·관계사", q: "___ he was tired, he finished the work.", c: ["Because", "Although", "So", "If"], a: "Although", why: "'피곤했지만 끝냈다'라는 반대 관계이므로 Although(~에도 불구하고)예요." },
  { cat: "접속사·관계사", q: "Call me ___ you arrive.", c: ["when", "during", "until", "while"], a: "when", why: "'도착하면(도착할 때)'이라는 시점이므로 when을 써요." },
  { cat: "접속사·관계사", q: "I'll wait here ___ you come back.", c: ["until", "by", "when", "since"], a: "until", why: "'돌아올 때까지 계속' 기다리는 것이므로 until을 써요." },
  { cat: "접속사·관계사", q: "This is the cafe ___ we first met.", c: ["which", "who", "where", "what"], a: "where", why: "장소(cafe)를 설명하는 관계부사는 where예요." },
  { cat: "접속사·관계사", q: "The man ___ lives next door is a doctor.", c: ["who", "which", "whose", "whom"], a: "who", why: "사람(the man)을 설명하고 주어 역할을 하므로 who를 써요." },
  { cat: "접속사·관계사", q: "I bought a book ___ was written by my professor.", c: ["who", "that", "what", "whose"], a: "that", why: "사물(book)을 설명하는 관계대명사는 that(또는 which)을 써요." },
  { cat: "접속사·관계사", q: "___ you hurry, you'll miss the train.", c: ["If", "Unless", "Because", "Though"], a: "Unless", why: "Unless는 '~하지 않으면'이라는 뜻으로 if ~ not과 같아요." },
];
