// 상황별 표현 데이터 — 상황 10가지 × 표현 8개
const PHRASES = [
  {
    name: "식당", icon: "🍽️",
    items: [
      { en: "A table for two, please.", ko: "두 명 자리 부탁해요." },
      { en: "Could we see the menu?", ko: "메뉴판 좀 볼 수 있을까요?" },
      { en: "What do you recommend?", ko: "추천 메뉴가 뭐예요?" },
      { en: "I'll have the steak, medium please.", ko: "스테이크 미디엄으로 주세요." },
      { en: "Could I get some more water?", ko: "물 좀 더 주시겠어요?" },
      { en: "This isn't what I ordered.", ko: "이건 제가 주문한 게 아닌데요." },
      { en: "Could we get the check, please?", ko: "계산서 좀 주시겠어요?" },
      { en: "Can I get this to go?", ko: "이거 포장해 갈 수 있나요?" },
    ],
  },
  {
    name: "카페", icon: "☕",
    items: [
      { en: "Can I get a medium iced americano?", ko: "아이스 아메리카노 미디엄 한 잔 주세요." },
      { en: "For here or to go?", ko: "여기서 드시나요, 가져가시나요? (직원)" },
      { en: "To go, please.", ko: "가져갈게요." },
      { en: "Can I get an extra shot?", ko: "샷 추가해 주시겠어요?" },
      { en: "With less ice, please.", ko: "얼음 적게 부탁해요." },
      { en: "Do you have any decaf options?", ko: "디카페인 되는 메뉴 있나요?" },
      { en: "Is this seat taken?", ko: "이 자리 주인 있나요?" },
      { en: "Could I get the wifi password?", ko: "와이파이 비밀번호 좀 알 수 있을까요?" },
    ],
  },
  {
    name: "쇼핑", icon: "🛍️",
    items: [
      { en: "I'm just looking, thanks.", ko: "그냥 둘러보는 중이에요, 감사해요." },
      { en: "Do you have this in a smaller size?", ko: "이거 더 작은 사이즈 있나요?" },
      { en: "Can I try this on?", ko: "이거 입어봐도 되나요?" },
      { en: "How much is this?", ko: "이거 얼마예요?" },
      { en: "Is this on sale?", ko: "이거 세일 중인가요?" },
      { en: "I'll take it.", ko: "이걸로 살게요." },
      { en: "Can I pay by card?", ko: "카드로 계산해도 되나요?" },
      { en: "Can I get a refund with this receipt?", ko: "이 영수증으로 환불받을 수 있나요?" },
    ],
  },
  {
    name: "공항·기내", icon: "✈️",
    items: [
      { en: "Where is the check-in counter for this flight?", ko: "이 항공편 체크인 카운터가 어디예요?" },
      { en: "I'd like to check in this bag.", ko: "이 가방을 부치고 싶어요." },
      { en: "Is the flight on time?", ko: "비행기가 제시간에 출발하나요?" },
      { en: "Could I have a window seat?", ko: "창가 자리로 주시겠어요?" },
      { en: "Could I get a blanket, please?", ko: "담요 좀 주시겠어요?" },
      { en: "Could you help me put this up?", ko: "이거 올리는 것 좀 도와주시겠어요?" },
      { en: "I'm here for travel.", ko: "여행하러 왔어요. (입국 심사)" },
      { en: "I'll stay for one week.", ko: "일주일 머물 예정이에요." },
    ],
  },
  {
    name: "호텔", icon: "🏨",
    items: [
      { en: "I have a reservation under Kim.", ko: "김으로 예약했어요." },
      { en: "What time is check-out?", ko: "체크아웃이 몇 시예요?" },
      { en: "Could I get a late check-out?", ko: "체크아웃 시간을 늦출 수 있을까요?" },
      { en: "Is breakfast included?", ko: "조식이 포함되어 있나요?" },
      { en: "The air conditioner isn't working.", ko: "에어컨이 작동하지 않아요." },
      { en: "Could I get some extra towels?", ko: "수건 좀 더 받을 수 있을까요?" },
      { en: "Can you keep my luggage until this afternoon?", ko: "오후까지 짐을 맡아주실 수 있나요?" },
      { en: "Could you call a taxi for me?", ko: "택시 좀 불러주시겠어요?" },
    ],
  },
  {
    name: "길 묻기", icon: "🗺️",
    items: [
      { en: "Excuse me, how do I get to the subway station?", ko: "실례합니다, 지하철역에 어떻게 가나요?" },
      { en: "Is it far from here?", ko: "여기서 먼가요?" },
      { en: "Can I walk there?", ko: "걸어갈 수 있나요?" },
      { en: "Go straight and turn left at the corner.", ko: "직진하다가 모퉁이에서 좌회전하세요." },
      { en: "It's right across from the bank.", ko: "은행 바로 맞은편이에요." },
      { en: "You can't miss it.", ko: "금방 찾으실 거예요." },
      { en: "I think I'm lost.", ko: "길을 잃은 것 같아요." },
      { en: "Could you show me on the map?", ko: "지도에서 좀 짚어주시겠어요?" },
    ],
  },
  {
    name: "병원·약국", icon: "💊",
    items: [
      { en: "I'd like to see a doctor.", ko: "진료를 받고 싶어요." },
      { en: "I have a fever and a sore throat.", ko: "열이 나고 목이 아파요." },
      { en: "How long have you had these symptoms?", ko: "이 증상이 얼마나 됐나요? (의사)" },
      { en: "Since yesterday morning.", ko: "어제 아침부터요." },
      { en: "Do I need a prescription for this?", ko: "이 약은 처방전이 필요한가요?" },
      { en: "Something for a headache, please.", ko: "두통약 좀 주세요." },
      { en: "Take one pill three times a day after meals.", ko: "하루 세 번 식후에 한 알씩 드세요. (약사)" },
      { en: "Are there any side effects?", ko: "부작용이 있나요?" },
    ],
  },
  {
    name: "전화·약속", icon: "📞",
    items: [
      { en: "Are you free this Friday?", ko: "이번 금요일에 시간 돼?" },
      { en: "Does seven work for you?", ko: "7시 괜찮아?" },
      { en: "Sorry, something came up.", ko: "미안, 일이 생겼어." },
      { en: "Can we reschedule?", ko: "다른 날로 바꿀 수 있을까?" },
      { en: "I'm running ten minutes late.", ko: "10분 정도 늦을 것 같아." },
      { en: "Where should we meet?", ko: "어디서 만날까?" },
      { en: "Sounds good. See you then!", ko: "좋아. 그때 보자!" },
      { en: "Sorry, you have the wrong number.", ko: "죄송하지만 전화 잘못 거셨어요." },
    ],
  },
  {
    name: "스몰토크", icon: "💬",
    items: [
      { en: "How's it going?", ko: "요즘 어때?" },
      { en: "Long time no see!", ko: "오랜만이야!" },
      { en: "What have you been up to?", ko: "그동안 뭐 하고 지냈어?" },
      { en: "The weather is amazing today, isn't it?", ko: "오늘 날씨 정말 좋네요, 그렇죠?" },
      { en: "Did you have a good weekend?", ko: "주말 잘 보냈어요?" },
      { en: "I've heard a lot about you.", ko: "말씀 많이 들었어요." },
      { en: "That reminds me of something.", ko: "그러고 보니 생각나는 게 있어." },
      { en: "Anyway, I'd better get going.", ko: "아무튼 난 슬슬 가봐야겠다." },
    ],
  },
  {
    name: "직장", icon: "💼",
    items: [
      { en: "Let's schedule a meeting for tomorrow.", ko: "내일 회의 일정을 잡읍시다." },
      { en: "Could you send me the file by email?", ko: "그 파일 이메일로 보내주시겠어요?" },
      { en: "I'll get back to you on that.", ko: "그 건은 확인하고 다시 알려드릴게요." },
      { en: "Sorry to cut in, but we're running out of time.", ko: "말씀 중에 죄송한데, 시간이 얼마 없네요." },
      { en: "Could you speak up a little?", ko: "조금만 크게 말씀해 주시겠어요?" },
      { en: "Let's move on to the next topic.", ko: "다음 주제로 넘어가죠." },
      { en: "I'm afraid I have a conflict at that time.", ko: "그 시간에는 다른 일정이 있어요." },
      { en: "Great work on the presentation.", ko: "발표 정말 잘하셨어요." },
    ],
  },
];
