// 섀도잉 문장 — lv 1: 초급(5~7단어), lv 2: 초중급(8~10단어), lv 3: 중급(11~14단어)
const SHADOW = [
  // ===== Level 1 (Beginner) =====
  { lv: 1, en: "Can I get some water?", ko: "물 좀 주시겠어요?" },
  { lv: 1, en: "I really like this song.", ko: "나 이 노래 정말 좋아해." },
  { lv: 1, en: "What time should we meet?", ko: "우리 몇 시에 만날까?" },
  { lv: 1, en: "This is my favorite place.", ko: "여기가 내가 제일 좋아하는 곳이야." },
  { lv: 1, en: "Let me check my schedule.", ko: "일정 좀 확인해볼게." },
  { lv: 1, en: "How was your day today?", ko: "오늘 하루 어땠어?" },
  { lv: 1, en: "I need a short break.", ko: "나 잠깐 쉬어야겠어." },
  { lv: 1, en: "Where is the bus stop?", ko: "버스 정류장이 어디예요?" },
  { lv: 1, en: "Could you say that again?", ko: "다시 한번 말씀해 주시겠어요?" },
  { lv: 1, en: "I'm on my way now.", ko: "지금 가는 중이야." },
  { lv: 1, en: "Let's grab lunch together tomorrow.", ko: "내일 같이 점심 먹자." },
  { lv: 1, en: "That sounds like a plan.", ko: "그거 좋은 생각이다." },
  { lv: 1, en: "Please turn on the light.", ko: "불 좀 켜줘." },
  { lv: 1, en: "I forgot to bring my wallet.", ko: "지갑 챙기는 걸 깜빡했어." },
  { lv: 1, en: "It's a little cold today.", ko: "오늘 조금 춥네." },
  // ===== Level 2 (Elementary) =====
  { lv: 2, en: "I'm thinking about going hiking with friends this weekend.", ko: "이번 주말에 친구들이랑 등산 갈까 생각 중이야." },
  { lv: 2, en: "Could you tell me how to get there?", ko: "거기 어떻게 가는지 알려주시겠어요?" },
  { lv: 2, en: "I usually drink coffee twice a day at work.", ko: "나는 회사에서 보통 하루에 커피를 두 번 마셔." },
  { lv: 2, en: "The weather looks nice, so let's eat outside.", ko: "날씨가 좋아 보이니까 밖에서 먹자." },
  { lv: 2, en: "I've been really busy with work these days.", ko: "요즘 일 때문에 정말 바빴어." },
  { lv: 2, en: "Do you know a good restaurant around here?", ko: "이 근처에 괜찮은 식당 알아?" },
  { lv: 2, en: "I'm not sure if I can make it tonight.", ko: "오늘 밤에 갈 수 있을지 잘 모르겠어." },
  { lv: 2, en: "She asked me to call her back later.", ko: "그녀가 나중에 다시 전화해 달래." },
  { lv: 2, en: "It took me an hour to get home yesterday.", ko: "어제 집에 가는 데 한 시간 걸렸어." },
  { lv: 2, en: "Let me know when you're ready to leave.", ko: "출발할 준비되면 알려줘." },
  { lv: 2, en: "I'd rather stay home and watch a movie.", ko: "난 그냥 집에서 영화 보는 게 낫겠어." },
  { lv: 2, en: "We should book the tickets before they sell out.", ko: "매진되기 전에 표를 예매해야 해." },
  { lv: 2, en: "He's getting better at speaking English every day.", ko: "그는 영어 말하기가 매일 늘고 있어." },
  { lv: 2, en: "Can you help me carry these bags upstairs?", ko: "이 가방들 위층으로 옮기는 것 좀 도와줄래?" },
  { lv: 2, en: "I forgot where I parked my car again.", ko: "차를 어디에 세웠는지 또 까먹었어." },
  // ===== Level 3 (Intermediate) =====
  { lv: 3, en: "If I had known about the traffic, I would have left earlier.", ko: "차가 막히는 걸 알았다면 더 일찍 출발했을 거야." },
  { lv: 3, en: "I've been meaning to try that new cafe everyone keeps talking about.", ko: "다들 얘기하는 그 새 카페에 가보려던 참이었어." },
  { lv: 3, en: "By the time we got to the station, the train had already left.", ko: "우리가 역에 도착했을 때는 기차가 이미 떠난 뒤였어." },
  { lv: 3, en: "She suggested that we take a short trip somewhere quiet next month.", ko: "그녀는 다음 달에 조용한 곳으로 짧은 여행을 가자고 제안했어." },
  { lv: 3, en: "The more I practice speaking English, the more confident I feel every day.", ko: "영어 말하기를 연습할수록 매일 자신감이 더 붙어." },
  { lv: 3, en: "I was about to give up when everything suddenly started working out.", ko: "포기하려던 참에 갑자기 모든 게 풀리기 시작했어." },
  { lv: 3, en: "Even though it was raining heavily, we decided to go out anyway.", ko: "비가 많이 왔는데도 우리는 그냥 나가기로 했어." },
  { lv: 3, en: "Could you explain that part again? I didn't quite catch it.", ko: "그 부분 다시 설명해 줄래? 잘 못 알아들었어." },
  { lv: 3, en: "It turns out the meeting was moved to next Friday afternoon.", ko: "알고 보니 회의가 다음 주 금요일 오후로 옮겨졌더라." },
  { lv: 3, en: "I honestly can't believe how quickly this year has gone by.", ko: "올해가 이렇게 빨리 지나갔다니 정말 믿기지 않아." },
  { lv: 3, en: "You should have seen his face when he heard the news.", ko: "그가 그 소식을 들었을 때 표정을 봤어야 해." },
  { lv: 3, en: "I'm trying to cut down on late-night snacks these days.", ko: "요즘 야식을 줄이려고 노력 중이야." },
  { lv: 3, en: "There's really no point worrying about things we can't control.", ko: "우리가 어쩔 수 없는 일을 걱정해봐야 소용없어." },
  { lv: 3, en: "Would you mind keeping an eye on my bag for a minute?", ko: "잠깐 제 가방 좀 봐주시겠어요?" },
  { lv: 3, en: "I ended up staying awake all night finishing the final report.", ko: "결국 최종 보고서를 끝내느라 밤을 꼬박 새웠어." },
];
