// 일상 회화 단어 100개 — w: 단어, m: 뜻, ex: 예문, exKo: 예문 해석
const WORDS = [
  { w: "appointment", m: "약속, 예약", ex: "I have a dentist appointment at three.", exKo: "3시에 치과 예약이 있어요." },
  { w: "available", m: "시간이 되는, 이용 가능한", ex: "Are you available this weekend?", exKo: "이번 주말에 시간 되세요?" },
  { w: "borrow", m: "빌리다", ex: "Can I borrow your charger for a minute?", exKo: "충전기 잠깐 빌려도 될까요?" },
  { w: "recommend", m: "추천하다", ex: "What dish would you recommend here?", exKo: "여기서 어떤 요리를 추천하세요?" },
  { w: "reservation", m: "예약", ex: "I made a reservation for two people.", exKo: "두 명으로 예약했어요." },
  { w: "delicious", m: "맛있는", ex: "This soup is really delicious.", exKo: "이 수프 정말 맛있어요." },
  { w: "crowded", m: "붐비는", ex: "The subway is so crowded in the morning.", exKo: "아침에 지하철이 너무 붐벼요." },
  { w: "convenient", m: "편리한", ex: "Living near the station is very convenient.", exKo: "역 근처에 사는 건 아주 편리해요." },
  { w: "expensive", m: "비싼", ex: "That bag looks nice but too expensive.", exKo: "저 가방 예쁜데 너무 비싸요." },
  { w: "receipt", m: "영수증", ex: "Could I get a receipt, please?", exKo: "영수증 좀 주시겠어요?" },
  { w: "refund", m: "환불", ex: "I'd like to get a refund for this shirt.", exKo: "이 셔츠 환불받고 싶어요." },
  { w: "exchange", m: "교환하다", ex: "Can I exchange this for a bigger size?", exKo: "이거 더 큰 사이즈로 교환할 수 있나요?" },
  { w: "discount", m: "할인", ex: "Is there a discount for students?", exKo: "학생 할인이 있나요?" },
  { w: "directions", m: "길 안내", ex: "Could you give me directions to the museum?", exKo: "박물관 가는 길 좀 알려주시겠어요?" },
  { w: "luggage", m: "짐, 수하물", ex: "My luggage is heavier than I thought.", exKo: "제 짐이 생각보다 무겁네요." },
  { w: "departure", m: "출발", ex: "The departure time was changed to noon.", exKo: "출발 시간이 정오로 바뀌었어요." },
  { w: "arrival", m: "도착", ex: "Please check the arrival gate on the screen.", exKo: "화면에서 도착 게이트를 확인해 주세요." },
  { w: "delay", m: "지연, 미루다", ex: "The flight was delayed by two hours.", exKo: "비행기가 두 시간 지연됐어요." },
  { w: "schedule", m: "일정", ex: "My schedule is pretty tight this week.", exKo: "이번 주는 일정이 꽤 빡빡해요." },
  { w: "cancel", m: "취소하다", ex: "I need to cancel my order.", exKo: "주문을 취소해야 해요." },
  { w: "confirm", m: "확인하다", ex: "Please confirm your booking by email.", exKo: "이메일로 예약을 확인해 주세요." },
  { w: "invite", m: "초대하다", ex: "She invited me to her housewarming party.", exKo: "그녀가 집들이에 저를 초대했어요." },
  { w: "celebrate", m: "축하하다, 기념하다", ex: "Let's celebrate your new job tonight!", exKo: "오늘 밤 네 새 직장 축하하자!" },
  { w: "favor", m: "부탁", ex: "Can I ask you a favor?", exKo: "부탁 하나 해도 될까요?" },
  { w: "promise", m: "약속하다", ex: "I promise I won't be late again.", exKo: "다시는 늦지 않겠다고 약속할게요." },
  { w: "forget", m: "잊다", ex: "Don't forget to bring your umbrella.", exKo: "우산 챙기는 거 잊지 마세요." },
  { w: "remember", m: "기억하다", ex: "Do you remember where we first met?", exKo: "우리가 처음 만난 곳 기억나요?" },
  { w: "decide", m: "결정하다", ex: "I can't decide what to eat for lunch.", exKo: "점심에 뭘 먹을지 결정을 못 하겠어요." },
  { w: "suggest", m: "제안하다", ex: "He suggested taking a break.", exKo: "그가 잠깐 쉬자고 제안했어요." },
  { w: "agree", m: "동의하다", ex: "I totally agree with you.", exKo: "당신 말에 전적으로 동의해요." },
  { w: "disagree", m: "반대하다", ex: "I'm sorry, but I disagree with that idea.", exKo: "미안하지만 그 생각에는 반대예요." },
  { w: "prefer", m: "더 좋아하다", ex: "I prefer coffee to tea.", exKo: "저는 차보다 커피를 더 좋아해요." },
  { w: "prepare", m: "준비하다", ex: "I'm preparing dinner for my family.", exKo: "가족을 위해 저녁을 준비하고 있어요." },
  { w: "arrive", m: "도착하다", ex: "What time did you arrive home?", exKo: "집에 몇 시에 도착했어요?" },
  { w: "leave", m: "떠나다, 두고 오다", ex: "I left my phone in the taxi.", exKo: "택시에 휴대폰을 두고 내렸어요." },
  { w: "hurry", m: "서두르다", ex: "Hurry up, or we'll miss the bus!", exKo: "서둘러, 안 그러면 버스 놓쳐!" },
  { w: "wait", m: "기다리다", ex: "Could you wait a moment, please?", exKo: "잠시만 기다려 주시겠어요?" },
  { w: "traffic", m: "교통(량)", ex: "The traffic is terrible on Friday evenings.", exKo: "금요일 저녁엔 교통이 끔찍해요." },
  { w: "weather", m: "날씨", ex: "The weather is perfect for a picnic.", exKo: "소풍 가기에 딱 좋은 날씨예요." },
  { w: "forecast", m: "예보", ex: "The forecast says it will rain tomorrow.", exKo: "예보에서 내일 비가 온대요." },
  { w: "temperature", m: "온도, 기온", ex: "The temperature dropped a lot last night.", exKo: "어젯밤에 기온이 많이 떨어졌어요." },
  { w: "umbrella", m: "우산", ex: "Take an umbrella just in case.", exKo: "혹시 모르니 우산 챙겨 가세요." },
  { w: "laundry", m: "빨래", ex: "I need to do the laundry today.", exKo: "오늘 빨래를 해야 해요." },
  { w: "grocery", m: "식료품", ex: "Let's stop by the grocery store.", exKo: "식료품 가게에 잠깐 들르자." },
  { w: "ingredient", m: "재료", ex: "We're missing one ingredient for the recipe.", exKo: "레시피에 필요한 재료 하나가 없어요." },
  { w: "recipe", m: "요리법", ex: "This recipe is easier than it looks.", exKo: "이 요리법은 보기보다 쉬워요." },
  { w: "flavor", m: "맛, 풍미", ex: "Which flavor of ice cream do you want?", exKo: "어떤 맛 아이스크림 먹을래?" },
  { w: "spicy", m: "매운", ex: "Is this dish very spicy?", exKo: "이 요리 많이 매워요?" },
  { w: "thirsty", m: "목마른", ex: "I'm so thirsty after the run.", exKo: "달리기하고 나니 목이 너무 말라요." },
  { w: "starving", m: "몹시 배고픈", ex: "Let's eat now. I'm starving!", exKo: "지금 먹자. 배고파 죽겠어!" },
  { w: "exhausted", m: "몹시 지친", ex: "I was exhausted after work yesterday.", exKo: "어제 퇴근하고 완전히 지쳤어요." },
  { w: "comfortable", m: "편안한", ex: "This sofa is really comfortable.", exKo: "이 소파 정말 편안해요." },
  { w: "nervous", m: "긴장한", ex: "I'm nervous about the interview.", exKo: "면접 때문에 긴장돼요." },
  { w: "excited", m: "신난, 기대되는", ex: "I'm so excited about the trip!", exKo: "여행 갈 생각에 너무 신나요!" },
  { w: "disappointed", m: "실망한", ex: "I was disappointed with the movie.", exKo: "그 영화에 실망했어요." },
  { w: "embarrassed", m: "당황한, 창피한", ex: "I felt embarrassed when I fell down.", exKo: "넘어졌을 때 정말 창피했어요." },
  { w: "proud", m: "자랑스러운", ex: "I'm proud of what you did.", exKo: "네가 한 일이 자랑스러워." },
  { w: "worried", m: "걱정하는", ex: "Don't be worried. Everything will be fine.", exKo: "걱정하지 마. 다 잘될 거야." },
  { w: "relieved", m: "안도한", ex: "I was relieved to hear the good news.", exKo: "좋은 소식을 듣고 안심했어요." },
  { w: "headache", m: "두통", ex: "I have a slight headache today.", exKo: "오늘 머리가 살짝 아파요." },
  { w: "medicine", m: "약", ex: "Take this medicine after meals.", exKo: "이 약은 식후에 드세요." },
  { w: "pharmacy", m: "약국", ex: "Is there a pharmacy near here?", exKo: "이 근처에 약국이 있나요?" },
  { w: "symptom", m: "증상", ex: "What symptoms do you have?", exKo: "어떤 증상이 있으세요?" },
  { w: "recover", m: "회복하다", ex: "I hope you recover soon.", exKo: "빨리 회복하길 바라요." },
  { w: "exercise", m: "운동(하다)", ex: "I try to exercise three times a week.", exKo: "일주일에 세 번 운동하려고 해요." },
  { w: "habit", m: "습관", ex: "Going to bed early is a good habit.", exKo: "일찍 자는 건 좋은 습관이에요." },
  { w: "neighborhood", m: "동네, 이웃", ex: "There's a nice park in my neighborhood.", exKo: "우리 동네에 좋은 공원이 있어요." },
  { w: "landlord", m: "집주인", ex: "The landlord fixed the heater quickly.", exKo: "집주인이 난방기를 빨리 고쳐줬어요." },
  { w: "utility", m: "공과금, 공공요금", ex: "The rent doesn't include utility bills.", exKo: "월세에 공과금은 포함되지 않아요." },
  { w: "repair", m: "수리하다", ex: "I need to repair my bicycle brakes.", exKo: "자전거 브레이크를 수리해야 해요." },
  { w: "appliance", m: "가전제품", ex: "This store sells kitchen appliances.", exKo: "이 가게는 주방 가전을 팔아요." },
  { w: "errand", m: "심부름, 볼일", ex: "I have a few errands to run today.", exKo: "오늘 볼일이 몇 가지 있어요." },
  { w: "package", m: "소포, 택배", ex: "A package arrived for you this morning.", exKo: "오늘 아침에 네 앞으로 택배가 왔어." },
  { w: "deliver", m: "배달하다", ex: "They deliver until ten at night.", exKo: "밤 10시까지 배달해줘요." },
  { w: "order", m: "주문(하다)", ex: "Are you ready to order?", exKo: "주문하시겠어요?" },
  { w: "takeout", m: "포장 음식", ex: "Let's just get takeout tonight.", exKo: "오늘 밤엔 그냥 포장해서 먹자." },
  { w: "split", m: "나누다 (비용 등)", ex: "Let's split the bill this time.", exKo: "이번엔 계산 나눠서 하자." },
  { w: "treat", m: "한턱내다, 대접", ex: "It's my treat today. Order anything.", exKo: "오늘은 내가 살게. 아무거나 시켜." },
  { w: "hang out", m: "어울려 놀다", ex: "Do you want to hang out this Saturday?", exKo: "이번 토요일에 같이 놀래?" },
  { w: "catch up", m: "밀린 이야기를 나누다", ex: "Let's grab coffee and catch up soon.", exKo: "조만간 커피 마시면서 밀린 얘기 하자." },
  { w: "show up", m: "나타나다", ex: "He didn't show up to the meeting.", exKo: "그는 모임에 나타나지 않았어요." },
  { w: "run into", m: "우연히 만나다", ex: "I ran into an old friend at the mall.", exKo: "쇼핑몰에서 옛 친구를 우연히 만났어요." },
  { w: "look forward to", m: "기대하다", ex: "I'm looking forward to seeing you.", exKo: "만나기를 기대하고 있어요." },
  { w: "figure out", m: "알아내다, 이해하다", ex: "I can't figure out how to use this app.", exKo: "이 앱 사용법을 모르겠어요." },
  { w: "give up", m: "포기하다", ex: "Don't give up. You're almost there.", exKo: "포기하지 마. 거의 다 왔어." },
  { w: "take care of", m: "돌보다, 처리하다", ex: "I'll take care of the dishes tonight.", exKo: "오늘 설거지는 내가 할게." },
  { w: "on time", m: "제시간에", ex: "The bus rarely comes on time here.", exKo: "여기 버스는 제시간에 오는 일이 드물어요." },
  { w: "in advance", m: "미리", ex: "You should book the tickets in advance.", exKo: "표는 미리 예매하는 게 좋아요." },
  { w: "by chance", m: "우연히", ex: "Do you know his number by chance?", exKo: "혹시 그의 번호 알아요?" },
  { w: "definitely", m: "확실히, 분명히", ex: "I'll definitely be there by seven.", exKo: "7시까지 꼭 갈게요." },
  { w: "actually", m: "사실은", ex: "Actually, I've never tried sushi before.", exKo: "사실 저 초밥 한 번도 안 먹어봤어요." },
  { w: "probably", m: "아마도", ex: "It will probably rain this afternoon.", exKo: "오늘 오후에 아마 비가 올 거예요." },
  { w: "recently", m: "최근에", ex: "Have you seen any good movies recently?", exKo: "최근에 좋은 영화 본 거 있어요?" },
  { w: "suddenly", m: "갑자기", ex: "The lights suddenly went out.", exKo: "갑자기 불이 나갔어요." },
  { w: "especially", m: "특히", ex: "I love fruit, especially watermelon.", exKo: "저는 과일을 좋아하는데, 특히 수박을요." },
  { w: "opinion", m: "의견", ex: "In my opinion, this plan is better.", exKo: "제 생각에는 이 계획이 더 나아요." },
  { w: "experience", m: "경험", ex: "That trip was an amazing experience.", exKo: "그 여행은 정말 놀라운 경험이었어요." },
  { w: "opportunity", m: "기회", ex: "This is a great opportunity to learn.", exKo: "이건 배울 수 있는 좋은 기회예요." },
  { w: "mistake", m: "실수", ex: "Everyone makes mistakes sometimes.", exKo: "누구나 가끔 실수를 해요." },
  { w: "improve", m: "향상시키다", ex: "I want to improve my speaking skills.", exKo: "말하기 실력을 키우고 싶어요." },
  // ===== 집 · 생활용품 =====
  { w: "drawer", m: "서랍", ex: "The scissors are in the top drawer.", exKo: "가위는 맨 위 서랍에 있어요." },
  { w: "closet", m: "옷장", ex: "My closet is full of clothes I never wear.", exKo: "옷장이 안 입는 옷으로 가득해요." },
  { w: "shelf", m: "선반", ex: "Put the books back on the shelf.", exKo: "책을 선반에 다시 올려놓으세요." },
  { w: "blanket", m: "담요", ex: "Do you need an extra blanket?", exKo: "담요 한 장 더 필요하세요?" },
  { w: "pillow", m: "베개", ex: "This pillow is too high for me.", exKo: "이 베개는 저한테 너무 높아요." },
  { w: "curtain", m: "커튼", ex: "Could you open the curtains?", exKo: "커튼 좀 열어줄래요?" },
  { w: "mirror", m: "거울", ex: "He checked his hair in the mirror.", exKo: "그는 거울로 머리를 확인했어요." },
  { w: "towel", m: "수건", ex: "Hang the wet towel outside.", exKo: "젖은 수건은 밖에 널어놔." },
  { w: "soap", m: "비누", ex: "We're almost out of soap.", exKo: "비누가 거의 다 떨어졌어요." },
  { w: "toothbrush", m: "칫솔", ex: "You should change your toothbrush often.", exKo: "칫솔은 자주 바꾸는 게 좋아요." },
  { w: "ceiling", m: "천장", ex: "There's a water stain on the ceiling.", exKo: "천장에 물 자국이 있어요." },
  { w: "stairs", m: "계단", ex: "Take the stairs instead of the elevator.", exKo: "엘리베이터 대신 계단을 이용하세요." },
  { w: "hallway", m: "복도", ex: "Don't run in the hallway.", exKo: "복도에서 뛰지 마세요." },
  { w: "vacuum", m: "진공청소기; 청소기를 돌리다", ex: "I vacuum the living room every morning.", exKo: "매일 아침 거실을 청소기로 밀어요." },
  { w: "broom", m: "빗자루", ex: "Sweep the floor with this broom.", exKo: "이 빗자루로 바닥을 쓸어." },
  { w: "trash", m: "쓰레기", ex: "Please take out the trash tonight.", exKo: "오늘 밤에 쓰레기 좀 내다 버려줘." },
  { w: "recycle", m: "재활용하다", ex: "We recycle plastic and paper separately.", exKo: "우리는 플라스틱과 종이를 분리해서 재활용해요." },
  { w: "faucet", m: "수도꼭지", ex: "The faucet keeps dripping.", exKo: "수도꼭지에서 물이 계속 떨어져요." },
  { w: "sink", m: "싱크대, 세면대", ex: "The dishes are piling up in the sink.", exKo: "싱크대에 설거지가 쌓이고 있어요." },
  { w: "stove", m: "가스레인지", ex: "Turn off the stove after cooking.", exKo: "요리 후에 가스레인지를 꺼주세요." },
  { w: "oven", m: "오븐", ex: "Preheat the oven to 180 degrees.", exKo: "오븐을 180도로 예열하세요." },
  { w: "microwave", m: "전자레인지", ex: "Heat it in the microwave for two minutes.", exKo: "전자레인지에 2분 돌려." },
  { w: "fridge", m: "냉장고", ex: "There's nothing to eat in the fridge.", exKo: "냉장고에 먹을 게 하나도 없어." },
  { w: "freezer", m: "냉동실", ex: "Keep the ice cream in the freezer.", exKo: "아이스크림은 냉동실에 보관해." },
  { w: "kettle", m: "주전자", ex: "The kettle is boiling.", exKo: "주전자 물이 끓고 있어요." },
  { w: "pan", m: "프라이팬", ex: "Heat some oil in the pan first.", exKo: "먼저 팬에 기름을 두르세요." },
  { w: "pot", m: "냄비", ex: "The soup is still in the pot.", exKo: "국이 아직 냄비에 있어요." },
  { w: "plate", m: "접시", ex: "Could you pass me a clean plate?", exKo: "깨끗한 접시 좀 건네줄래요?" },
  { w: "bowl", m: "그릇, 사발", ex: "She ate a big bowl of rice.", exKo: "그녀는 밥을 한 그릇 가득 먹었어요." },
  { w: "napkin", m: "냅킨", ex: "Can we get some more napkins?", exKo: "냅킨 좀 더 주시겠어요?" },
  { w: "lid", m: "뚜껑", ex: "I can't open this jar lid.", exKo: "이 병뚜껑이 안 열려요." },
  { w: "leftover", m: "남은 음식", ex: "We had leftovers for lunch.", exKo: "점심으로 남은 음식을 먹었어요." },
  { w: "outlet", m: "콘센트", ex: "Is there an outlet near this seat?", exKo: "이 자리 근처에 콘센트 있나요?" },
  { w: "plug", m: "플러그(를 꽂다)", ex: "Plug in the charger over there.", exKo: "충전기는 저쪽에 꽂아." },
  { w: "battery", m: "배터리, 건전지", ex: "My phone battery dies so fast.", exKo: "내 폰 배터리가 너무 빨리 닳아." },
  { w: "bulb", m: "전구", ex: "The bulb in the bathroom burned out.", exKo: "화장실 전구가 나갔어요." },
  { w: "ladder", m: "사다리", ex: "Hold the ladder while I climb.", exKo: "내가 올라가는 동안 사다리 좀 잡아줘." },
  { w: "tool", m: "도구, 공구", ex: "Do you have any tools for this?", exKo: "이거 고칠 공구 있어요?" },
  { w: "glue", m: "접착제, 풀", ex: "Fix it with some strong glue.", exKo: "강력 접착제로 붙여." },
  { w: "scissors", m: "가위", ex: "Be careful with those scissors.", exKo: "그 가위 조심해서 써." },
  { w: "tape", m: "테이프", ex: "Seal the box with tape.", exKo: "상자를 테이프로 봉하세요." },
  { w: "string", m: "끈, 줄", ex: "Tie the bag with this string.", exKo: "이 끈으로 봉지를 묶어." },
  // ===== 돈 · 쇼핑 =====
  { w: "wallet", m: "지갑", ex: "I left my wallet at home.", exKo: "지갑을 집에 두고 왔어요." },
  { w: "cash", m: "현금", ex: "Do you take cash only?", exKo: "현금만 받나요?" },
  { w: "coin", m: "동전", ex: "I need coins for the vending machine.", exKo: "자판기에 쓸 동전이 필요해요." },
  { w: "change", m: "거스름돈; 바꾸다", ex: "Keep the change, please.", exKo: "거스름돈은 가지세요." },
  { w: "price", m: "가격", ex: "The price went up again.", exKo: "가격이 또 올랐어요." },
  { w: "cost", m: "비용; (비용이) 들다", ex: "How much does it cost per month?", exKo: "한 달에 비용이 얼마나 들어요?" },
  { w: "afford", m: "(금전적) 여유가 되다", ex: "I can't afford a new car right now.", exKo: "지금은 새 차 살 여유가 없어요." },
  { w: "budget", m: "예산", ex: "Let's plan a trip within our budget.", exKo: "예산 안에서 여행을 계획하자." },
  { w: "savings", m: "저축, 모은 돈", ex: "I used my savings to pay the deposit.", exKo: "보증금을 내려고 모은 돈을 썼어요." },
  { w: "deposit", m: "보증금; 입금하다", ex: "The deposit will be refunded later.", exKo: "보증금은 나중에 환불돼요." },
  { w: "withdraw", m: "(돈을) 인출하다", ex: "I need to withdraw some money.", exKo: "돈을 좀 인출해야 해요." },
  { w: "transfer", m: "이체하다; 갈아타다", ex: "I'll transfer the money tonight.", exKo: "오늘 밤에 돈을 이체할게요." },
  { w: "loan", m: "대출", ex: "He took out a loan for the house.", exKo: "그는 집 때문에 대출을 받았어요." },
  { w: "debt", m: "빚", ex: "She finally paid off her debt.", exKo: "그녀는 마침내 빚을 다 갚았어요." },
  { w: "interest", m: "이자; 관심", ex: "The interest rate is going up.", exKo: "이자율이 오르고 있어요." },
  { w: "tax", m: "세금", ex: "Is tax included in this price?", exKo: "이 가격에 세금이 포함되어 있나요?" },
  { w: "salary", m: "월급, 급여", ex: "My salary comes in on the 25th.", exKo: "월급은 25일에 들어와요." },
  { w: "income", m: "수입, 소득", ex: "His income doubled in two years.", exKo: "그의 수입은 2년 만에 두 배가 됐어요." },
  { w: "expense", m: "지출, 비용", ex: "Food is my biggest expense.", exKo: "식비가 제일 큰 지출이에요." },
  { w: "allowance", m: "용돈", ex: "I give my son a weekly allowance.", exKo: "아들에게 매주 용돈을 줘요." },
  { w: "tip", m: "팁; 조언", ex: "Should we leave a tip here?", exKo: "여기서 팁을 남겨야 하나요?" },
  { w: "fee", m: "수수료, 요금", ex: "There's a small delivery fee.", exKo: "약간의 배달 수수료가 있어요." },
  { w: "fare", m: "(교통) 요금", ex: "The bus fare went up last month.", exKo: "지난달에 버스 요금이 올랐어요." },
  { w: "bill", m: "고지서, 계산서", ex: "The electricity bill was huge this month.", exKo: "이번 달 전기 요금이 어마어마했어요." },
  { w: "coupon", m: "쿠폰", ex: "This coupon expires tomorrow.", exKo: "이 쿠폰은 내일 만료돼요." },
  { w: "membership", m: "회원(권)", ex: "The gym membership is half price now.", exKo: "지금 헬스장 회원권이 반값이에요." },
  { w: "bargain", m: "싸게 산 물건; 흥정하다", ex: "This coat was a real bargain.", exKo: "이 코트 진짜 싸게 잘 샀어." },
  { w: "quality", m: "품질", ex: "The quality is worth the price.", exKo: "품질이 가격값을 해요." },
  { w: "brand", m: "상표, 브랜드", ex: "I don't really care about brands.", exKo: "저는 브랜드는 별로 신경 안 써요." },
  { w: "warranty", m: "품질 보증(서)", ex: "The laptop has a two-year warranty.", exKo: "그 노트북은 2년 보증이 돼요." },
  { w: "purchase", m: "구매(하다)", ex: "Keep the receipt after your purchase.", exKo: "구매 후 영수증을 보관하세요." },
  { w: "payment", m: "지불, 결제", ex: "Which payment method do you prefer?", exKo: "어떤 결제 방법을 선호하세요?" },
  { w: "cart", m: "카트, 장바구니", ex: "My cart is already full.", exKo: "카트가 벌써 가득 찼어요." },
  { w: "aisle", m: "통로", ex: "Snacks are in aisle five.", exKo: "과자는 5번 통로에 있어요." },
  { w: "counter", m: "계산대", ex: "Please pay at the counter.", exKo: "계산대에서 결제해 주세요." },
  { w: "wrap", m: "포장하다, 싸다", ex: "Could you wrap it as a gift?", exKo: "선물용으로 포장해 주시겠어요?" },
  // ===== 옷 =====
  { w: "sleeve", m: "소매", ex: "The sleeves are a bit long.", exKo: "소매가 조금 길어요." },
  { w: "collar", m: "옷깃", ex: "Your collar is folded inward.", exKo: "네 옷깃이 안으로 접혔어." },
  { w: "button", m: "단추", ex: "A button came off my shirt.", exKo: "셔츠에서 단추가 하나 떨어졌어요." },
  { w: "zipper", m: "지퍼", ex: "The zipper on my bag is stuck.", exKo: "가방 지퍼가 걸렸어요." },
  { w: "pocket", m: "주머니", ex: "My keys are in my coat pocket.", exKo: "열쇠는 코트 주머니에 있어요." },
  { w: "pattern", m: "무늬, 패턴", ex: "I like the pattern on this dress.", exKo: "이 원피스 무늬가 마음에 들어요." },
  { w: "plain", m: "무늬 없는; 담백한", ex: "I'll take the plain white shirt.", exKo: "무늬 없는 흰 셔츠로 할게요." },
  { w: "fabric", m: "천, 원단", ex: "This fabric feels really soft.", exKo: "이 원단 감촉이 정말 부드러워요." },
  { w: "cotton", m: "면", ex: "I prefer cotton shirts in summer.", exKo: "여름엔 면 셔츠가 좋아요." },
  { w: "leather", m: "가죽", ex: "He bought a leather jacket.", exKo: "그는 가죽 재킷을 샀어요." },
  { w: "wool", m: "양모, 울", ex: "This wool sweater is itchy.", exKo: "이 울 스웨터는 따가워요." },
  { w: "tight", m: "꽉 끼는", ex: "These jeans are too tight.", exKo: "이 청바지는 너무 꽉 껴요." },
  { w: "loose", m: "헐렁한", ex: "I like loose and comfortable clothes.", exKo: "저는 헐렁하고 편한 옷이 좋아요." },
  { w: "fit", m: "(몸에) 맞다", ex: "This jacket fits you perfectly.", exKo: "이 재킷 너한테 딱 맞는다." },
  { w: "outfit", m: "옷차림, 복장", ex: "I love your outfit today!", exKo: "오늘 옷차림 너무 예쁘다!" },
  { w: "casual", m: "캐주얼한, 격식 없는", ex: "The dress code is casual on Fridays.", exKo: "금요일은 복장이 자유예요." },
  { w: "formal", m: "격식 있는", ex: "Do I need formal clothes for the wedding?", exKo: "결혼식에 정장을 입어야 하나요?" },
  { w: "iron", m: "다리미(질하다)", ex: "I need to iron this shirt.", exKo: "이 셔츠를 다려야 해요." },
  { w: "fold", m: "개다, 접다", ex: "Fold the laundry and put it away.", exKo: "빨래를 개서 정리해." },
  { w: "stain", m: "얼룩", ex: "I got a coffee stain on my shirt.", exKo: "셔츠에 커피 얼룩이 묻었어요." },
  { w: "wrinkle", m: "주름; 구겨지다", ex: "This fabric wrinkles easily.", exKo: "이 천은 쉽게 구겨져요." },
  { w: "try on", m: "입어 보다", ex: "Can I try on these shoes?", exKo: "이 신발 신어봐도 되나요?" },
  // ===== 시간 표현 =====
  { w: "dawn", m: "새벽", ex: "We left home at dawn.", exKo: "우리는 새벽에 집을 나섰어요." },
  { w: "noon", m: "정오, 낮 12시", ex: "Let's meet at noon.", exKo: "정오에 만나자." },
  { w: "midnight", m: "자정", ex: "I stayed up until midnight.", exKo: "자정까지 안 자고 있었어요." },
  { w: "weekday", m: "평일", ex: "The cafe is quiet on weekdays.", exKo: "그 카페는 평일엔 한산해요." },
  { w: "anniversary", m: "기념일", ex: "Today is our wedding anniversary.", exKo: "오늘은 우리 결혼기념일이에요." },
  { w: "deadline", m: "마감 기한", ex: "The deadline is this Friday.", exKo: "마감이 이번 주 금요일이에요." },
  { w: "moment", m: "순간, 잠깐", ex: "Just a moment, please.", exKo: "잠시만요." },
  { w: "meanwhile", m: "그동안에, 한편", ex: "Meanwhile, I'll set the table.", exKo: "그동안 나는 상을 차릴게." },
  { w: "afterwards", m: "그 후에", ex: "We watched a movie and had dinner afterwards.", exKo: "영화를 보고 나서 저녁을 먹었어요." },
  { w: "beforehand", m: "미리, 사전에", ex: "Let me know beforehand if you can't come.", exKo: "못 오면 미리 알려줘." },
  { w: "lately", m: "최근에", ex: "I've been so busy lately.", exKo: "요즘 너무 바빴어요." },
  { w: "nowadays", m: "요즘에는", ex: "Nowadays everyone shops online.", exKo: "요즘은 다들 온라인으로 쇼핑해요." },
  { w: "occasionally", m: "가끔", ex: "I occasionally eat out alone.", exKo: "가끔 혼자 외식해요." },
  { w: "frequently", m: "자주", ex: "This word is frequently used.", exKo: "이 단어는 자주 쓰여요." },
  { w: "rarely", m: "드물게, 좀처럼 ~않다", ex: "He rarely gets angry.", exKo: "그는 좀처럼 화를 내지 않아요." },
  { w: "immediately", m: "즉시", ex: "Call me immediately if anything happens.", exKo: "무슨 일 있으면 즉시 전화해." },
  { w: "eventually", m: "결국", ex: "Eventually, everything worked out.", exKo: "결국 모든 게 잘 풀렸어요." },
  { w: "temporarily", m: "일시적으로", ex: "The store is temporarily closed.", exKo: "그 가게는 일시적으로 문을 닫았어요." },
  { w: "permanently", m: "영구적으로", ex: "He moved abroad permanently.", exKo: "그는 아예 해외로 이주했어요." },
  { w: "instantly", m: "곧바로", ex: "She replied instantly.", exKo: "그녀는 곧바로 답장했어요." },
  // ===== 음식 · 요리 =====
  { w: "appetizer", m: "애피타이저, 전채", ex: "We ordered an appetizer to share.", exKo: "나눠 먹을 애피타이저를 시켰어요." },
  { w: "dessert", m: "디저트, 후식", ex: "Save some room for dessert.", exKo: "디저트 먹을 배는 남겨둬." },
  { w: "beverage", m: "음료", ex: "Beverages are sold separately.", exKo: "음료는 따로 판매돼요." },
  { w: "dish", m: "요리; 접시", ex: "What's the most popular dish here?", exKo: "여기서 제일 인기 있는 요리가 뭐예요?" },
  { w: "portion", m: "1인분, 양", ex: "The portions here are huge.", exKo: "여기는 양이 엄청 많아요." },
  { w: "refill", m: "리필(하다)", ex: "Can I get a refill, please?", exKo: "리필해 주시겠어요?" },
  { w: "sour", m: "신, 시큼한", ex: "This kimchi is a little sour.", exKo: "이 김치는 약간 셔요." },
  { w: "bitter", m: "쓴", ex: "The coffee tastes too bitter.", exKo: "커피가 너무 써요." },
  { w: "salty", m: "짠", ex: "The soup is a bit salty for me.", exKo: "국이 저한테는 좀 짜요." },
  { w: "bland", m: "싱거운", ex: "The food was healthy but bland.", exKo: "음식이 건강하긴 한데 싱거웠어요." },
  { w: "crispy", m: "바삭한", ex: "The chicken is perfectly crispy.", exKo: "치킨이 완벽하게 바삭해요." },
  { w: "tender", m: "(고기가) 연한", ex: "The steak was so tender.", exKo: "스테이크가 정말 연했어요." },
  { w: "chewy", m: "쫄깃한", ex: "I love chewy rice cakes.", exKo: "저는 쫄깃한 떡을 좋아해요." },
  { w: "greasy", m: "기름진", ex: "I should avoid greasy food.", exKo: "기름진 음식은 피해야 해요." },
  { w: "rotten", m: "썩은, 상한", ex: "This banana smells rotten.", exKo: "이 바나나 상한 냄새가 나." },
  { w: "ripe", m: "익은", ex: "Wait until the avocado is ripe.", exKo: "아보카도가 익을 때까지 기다려." },
  { w: "raw", m: "날것의", ex: "Do you eat raw fish?", exKo: "날생선(회) 먹을 수 있어요?" },
  { w: "boil", m: "끓이다, 삶다", ex: "Boil the eggs for ten minutes.", exKo: "달걀을 10분간 삶으세요." },
  { w: "fry", m: "볶다, 튀기다", ex: "Fry the onions until golden.", exKo: "양파를 노릇해질 때까지 볶으세요." },
  { w: "grill", m: "(불에) 굽다", ex: "Let's grill some meat this weekend.", exKo: "이번 주말에 고기 구워 먹자." },
  { w: "steam", m: "찌다; 증기", ex: "Steam the vegetables lightly.", exKo: "채소를 살짝 찌세요." },
  { w: "chop", m: "썰다, 다지다", ex: "Chop the garlic finely.", exKo: "마늘을 잘게 다지세요." },
  { w: "slice", m: "얇게 썰다; 한 조각", ex: "Slice the bread thinly.", exKo: "빵을 얇게 썰어." },
  { w: "peel", m: "껍질을 벗기다", ex: "Peel the potatoes first.", exKo: "먼저 감자 껍질을 벗기세요." },
  { w: "stir", m: "젓다", ex: "Stir the sauce slowly.", exKo: "소스를 천천히 저으세요." },
  { w: "pour", m: "붓다, 따르다", ex: "Pour the water into the pot.", exKo: "물을 냄비에 부으세요." },
  { w: "spill", m: "쏟다, 흘리다", ex: "I spilled coffee on my laptop.", exKo: "노트북에 커피를 쏟았어요." },
  { w: "sip", m: "홀짝이다; 한 모금", ex: "She took a sip of tea.", exKo: "그녀는 차를 한 모금 마셨어요." },
  { w: "chew", m: "씹다", ex: "Chew your food slowly.", exKo: "음식을 천천히 씹어." },
  { w: "swallow", m: "삼키다", ex: "It hurts when I swallow.", exKo: "삼킬 때 아파요." },
  { w: "bite", m: "한 입; 물다", ex: "Can I have a bite?", exKo: "한 입만 먹어도 돼?" },
  { w: "grab a bite", m: "간단히 먹다", ex: "Let's grab a bite before the movie.", exKo: "영화 보기 전에 간단히 뭐 좀 먹자." },
  { w: "cuisine", m: "요리(문화)", ex: "I'm a big fan of Thai cuisine.", exKo: "저는 태국 요리를 정말 좋아해요." },
  { w: "vegetarian", m: "채식주의자(의)", ex: "Do you have vegetarian options?", exKo: "채식 메뉴가 있나요?" },
  { w: "organic", m: "유기농의", ex: "Organic vegetables cost more.", exKo: "유기농 채소는 더 비싸요." },
  { w: "frozen", m: "냉동된", ex: "I keep frozen dumplings for busy days.", exKo: "바쁜 날을 위해 냉동만두를 사둬요." },
  { w: "dairy", m: "유제품(의)", ex: "She can't eat dairy products.", exKo: "그녀는 유제품을 못 먹어요." },
  { w: "grain", m: "곡물", ex: "Whole grains are good for you.", exKo: "통곡물은 몸에 좋아요." },
  { w: "seafood", m: "해산물", ex: "This town is famous for seafood.", exKo: "이 동네는 해산물로 유명해요." },
  { w: "snack", m: "간식", ex: "I always keep snacks in my desk.", exKo: "책상에 항상 간식을 놔둬요." },
  // ===== 여행 =====
  { w: "passport", m: "여권", ex: "My passport expires next year.", exKo: "제 여권은 내년에 만료돼요." },
  { w: "visa", m: "비자", ex: "Do Koreans need a visa for that country?", exKo: "한국인은 그 나라 갈 때 비자가 필요해요?" },
  { w: "customs", m: "세관", ex: "It took a while to pass through customs.", exKo: "세관 통과에 시간이 좀 걸렸어요." },
  { w: "boarding", m: "탑승", ex: "Boarding starts at gate 12.", exKo: "12번 게이트에서 탑승이 시작돼요." },
  { w: "destination", m: "목적지", ex: "We finally arrived at our destination.", exKo: "드디어 목적지에 도착했어요." },
  { w: "itinerary", m: "여행 일정표", ex: "I'll send you the full itinerary.", exKo: "전체 일정표를 보내줄게요." },
  { w: "sightseeing", m: "관광", ex: "We went sightseeing all day.", exKo: "하루 종일 관광을 했어요." },
  { w: "landmark", m: "명소, 랜드마크", ex: "The tower is the city's most famous landmark.", exKo: "그 타워는 도시에서 가장 유명한 명소예요." },
  { w: "souvenir", m: "기념품", ex: "I bought souvenirs for my coworkers.", exKo: "동료들 줄 기념품을 샀어요." },
  { w: "tourist", m: "관광객", ex: "The beach was full of tourists.", exKo: "해변이 관광객으로 가득했어요." },
  { w: "journey", m: "여정, 여행", ex: "It was a long but fun journey.", exKo: "길었지만 즐거운 여정이었어요." },
  { w: "abroad", m: "해외에(서)", ex: "She's studying abroad in Canada.", exKo: "그녀는 캐나다에서 유학 중이에요." },
  { w: "overseas", m: "해외의, 해외로", ex: "He often travels overseas for work.", exKo: "그는 일 때문에 해외 출장이 잦아요." },
  { w: "embassy", m: "대사관", ex: "Contact the embassy if you lose your passport.", exKo: "여권을 잃어버리면 대사관에 연락하세요." },
  { w: "currency", m: "통화, 화폐", ex: "What currency do they use there?", exKo: "거기서는 어떤 화폐를 써요?" },
  { w: "accommodation", m: "숙소", ex: "The accommodation was clean and cozy.", exKo: "숙소가 깨끗하고 아늑했어요." },
  { w: "suitcase", m: "여행 가방, 캐리어", ex: "My suitcase is over the weight limit.", exKo: "제 캐리어가 무게 제한을 넘었어요." },
  { w: "backpack", m: "배낭", ex: "He traveled Europe with one backpack.", exKo: "그는 배낭 하나로 유럽을 여행했어요." },
  { w: "route", m: "경로, 노선", ex: "This route avoids the traffic.", exKo: "이 경로는 차 막히는 걸 피할 수 있어요." },
  { w: "platform", m: "승강장", ex: "The train leaves from platform three.", exKo: "기차는 3번 승강장에서 출발해요." },
  { w: "timetable", m: "시간표", ex: "Check the bus timetable first.", exKo: "버스 시간표부터 확인해." },
  { w: "round trip", m: "왕복 (여행)", ex: "A round trip ticket is cheaper.", exKo: "왕복표가 더 싸요." },
  { w: "one way", m: "편도", ex: "I only need a one way ticket.", exKo: "편도 표만 필요해요." },
  { w: "window seat", m: "창가 자리", ex: "I'd like a window seat, please.", exKo: "창가 자리로 부탁드려요." },
  { w: "view", m: "전망, 경치", ex: "The room has an amazing ocean view.", exKo: "그 방은 바다 전망이 끝내줘요." },
  { w: "scenery", m: "풍경", ex: "The scenery along the coast was breathtaking.", exKo: "해안가 풍경이 숨 막히게 아름다웠어요." },
  // ===== 교통 · 길 =====
  { w: "pedestrian", m: "보행자", ex: "Watch out for pedestrians.", exKo: "보행자를 조심하세요." },
  { w: "crosswalk", m: "횡단보도", ex: "Cross only at the crosswalk.", exKo: "횡단보도로만 건너세요." },
  { w: "sidewalk", m: "인도, 보도", ex: "Bikes shouldn't ride on the sidewalk.", exKo: "자전거는 인도로 다니면 안 돼요." },
  { w: "intersection", m: "교차로", ex: "Turn left at the next intersection.", exKo: "다음 교차로에서 좌회전하세요." },
  { w: "lane", m: "차선", ex: "Stay in your lane.", exKo: "차선을 지키세요." },
  { w: "highway", m: "고속도로", ex: "The highway was jammed for hours.", exKo: "고속도로가 몇 시간째 꽉 막혔어요." },
  { w: "detour", m: "우회(로)", ex: "We had to take a detour because of construction.", exKo: "공사 때문에 우회해야 했어요." },
  { w: "shortcut", m: "지름길", ex: "I know a shortcut to the station.", exKo: "역까지 가는 지름길을 알아요." },
  { w: "commute", m: "통근(하다)", ex: "My commute takes about an hour.", exKo: "통근에 한 시간쯤 걸려요." },
  { w: "rush hour", m: "혼잡 시간대", ex: "Avoid the subway during rush hour.", exKo: "러시아워에는 지하철을 피해." },
  { w: "license", m: "면허(증)", ex: "I finally got my driver's license!", exKo: "드디어 운전면허를 땄어요!" },
  { w: "parking lot", m: "주차장", ex: "The parking lot is full.", exKo: "주차장이 만차예요." },
  { w: "gas station", m: "주유소", ex: "Let's stop at the next gas station.", exKo: "다음 주유소에서 잠깐 서자." },
  { w: "flat tire", m: "펑크 난 타이어", ex: "We got a flat tire on the way.", exKo: "가는 길에 타이어가 펑크 났어요." },
  { w: "seatbelt", m: "안전벨트", ex: "Fasten your seatbelt, please.", exKo: "안전벨트를 매주세요." },
  { w: "fine", m: "벌금; 괜찮은", ex: "He paid a fine for speeding.", exKo: "그는 과속으로 벌금을 냈어요." },
  { w: "vehicle", m: "차량", ex: "This lane is for emergency vehicles.", exKo: "이 차선은 긴급 차량용이에요." },
  // ===== 건강 · 몸 =====
  { w: "fever", m: "열", ex: "The baby has a slight fever.", exKo: "아기가 미열이 있어요." },
  { w: "cough", m: "기침(하다)", ex: "I can't stop coughing.", exKo: "기침이 멈추질 않아요." },
  { w: "sneeze", m: "재채기(하다)", ex: "Dust makes me sneeze.", exKo: "먼지 때문에 재채기가 나요." },
  { w: "sore", m: "아픈, 따가운", ex: "I have a sore throat.", exKo: "목이 아파요." },
  { w: "runny nose", m: "콧물", ex: "I've had a runny nose all day.", exKo: "하루 종일 콧물이 나요." },
  { w: "dizzy", m: "어지러운", ex: "I feel dizzy when I stand up.", exKo: "일어설 때 어지러워요." },
  { w: "nausea", m: "메스꺼움", ex: "The medicine can cause nausea.", exKo: "그 약은 메스꺼움을 유발할 수 있어요." },
  { w: "bruise", m: "멍", ex: "Where did you get that bruise?", exKo: "그 멍은 어디서 생겼어?" },
  { w: "wound", m: "상처", ex: "Clean the wound with water first.", exKo: "먼저 상처를 물로 씻어내세요." },
  { w: "bandage", m: "붕대, 밴드", ex: "Put a bandage on the cut.", exKo: "베인 곳에 밴드를 붙여." },
  { w: "injection", m: "주사", ex: "The injection hurt a little.", exKo: "주사가 조금 아팠어요." },
  { w: "vaccine", m: "백신", ex: "Did you get the flu vaccine this year?", exKo: "올해 독감 백신 맞았어요?" },
  { w: "clinic", m: "의원, 클리닉", ex: "There's a good clinic near my house.", exKo: "집 근처에 괜찮은 의원이 있어요." },
  { w: "dentist", m: "치과 (의사)", ex: "I'm scared of going to the dentist.", exKo: "치과 가는 게 무서워요." },
  { w: "cavity", m: "충치", ex: "The dentist found two cavities.", exKo: "치과에서 충치 두 개를 발견했어요." },
  { w: "allergy", m: "알레르기", ex: "I have a peanut allergy.", exKo: "저는 땅콩 알레르기가 있어요." },
  { w: "digest", m: "소화하다", ex: "Walking helps you digest food.", exKo: "걷기는 소화에 도움이 돼요." },
  { w: "stomachache", m: "복통, 배탈", ex: "I got a stomachache from eating too fast.", exKo: "너무 급하게 먹어서 배탈이 났어요." },
  { w: "insomnia", m: "불면증", ex: "Coffee at night gives me insomnia.", exKo: "밤에 커피를 마시면 잠이 안 와요." },
  { w: "fatigue", m: "피로", ex: "Regular breaks reduce fatigue.", exKo: "규칙적인 휴식은 피로를 줄여줘요." },
  { w: "muscle", m: "근육", ex: "My muscles ache after the workout.", exKo: "운동 후에 근육이 쑤셔요." },
  { w: "weight", m: "체중, 무게", ex: "I'm trying to keep my weight steady.", exKo: "체중을 유지하려고 노력 중이에요." },
  { w: "nutrition", m: "영양", ex: "Good nutrition matters more than dieting.", exKo: "다이어트보다 영양이 더 중요해요." },
  { w: "protein", m: "단백질", ex: "Eggs are a cheap source of protein.", exKo: "달걀은 저렴한 단백질 공급원이에요." },
  { w: "vitamin", m: "비타민", ex: "I take vitamins every morning.", exKo: "매일 아침 비타민을 챙겨 먹어요." },
  { w: "calorie", m: "칼로리, 열량", ex: "This salad is low in calories.", exKo: "이 샐러드는 칼로리가 낮아요." },
  { w: "checkup", m: "건강 검진", ex: "I have a regular checkup next week.", exKo: "다음 주에 정기 검진이 있어요." },
  { w: "prescription", m: "처방전", ex: "You need a prescription for this medicine.", exKo: "이 약은 처방전이 필요해요." },
  { w: "swollen", m: "부은", ex: "My ankle is swollen.", exKo: "발목이 부었어요." },
  { w: "itchy", m: "가려운", ex: "My eyes get itchy in spring.", exKo: "봄에는 눈이 가려워요." },
  { w: "heal", m: "낫다, 치유되다", ex: "The cut healed quickly.", exKo: "베인 상처가 금방 나았어요." },
  { w: "injury", m: "부상", ex: "He missed the game because of an injury.", exKo: "그는 부상 때문에 경기에 못 나갔어요." },
  { w: "emergency", m: "응급 (상황)", ex: "In an emergency, call 119.", exKo: "응급 상황에는 119에 전화하세요." },
  { w: "ambulance", m: "구급차", ex: "Someone called an ambulance right away.", exKo: "누군가 바로 구급차를 불렀어요." },
  { w: "first aid", m: "응급 처치", ex: "Everyone should learn basic first aid.", exKo: "누구나 기본 응급 처치는 배워야 해요." },
  // ===== 날씨 · 자연 =====
  { w: "humid", m: "습한", ex: "Korean summers are hot and humid.", exKo: "한국 여름은 덥고 습해요." },
  { w: "chilly", m: "쌀쌀한", ex: "It's getting chilly in the evenings.", exKo: "저녁엔 점점 쌀쌀해지네요." },
  { w: "freezing", m: "몹시 추운", ex: "It's freezing outside today!", exKo: "오늘 밖이 얼어붙게 추워요!" },
  { w: "breeze", m: "산들바람", ex: "A cool breeze came through the window.", exKo: "창문으로 시원한 바람이 들어왔어요." },
  { w: "storm", m: "폭풍", ex: "The storm knocked down some trees.", exKo: "폭풍에 나무 몇 그루가 쓰러졌어요." },
  { w: "thunder", m: "천둥", ex: "The thunder scared my dog.", exKo: "천둥소리에 우리 개가 겁먹었어요." },
  { w: "lightning", m: "번개", ex: "Lightning lit up the whole sky.", exKo: "번개가 하늘을 온통 밝혔어요." },
  { w: "shower", m: "소나기; 샤워", ex: "We got caught in a sudden shower.", exKo: "갑작스러운 소나기를 만났어요." },
  { w: "fog", m: "안개", ex: "Thick fog covered the bridge.", exKo: "짙은 안개가 다리를 덮었어요." },
  { w: "frost", m: "서리", ex: "There was frost on the car this morning.", exKo: "오늘 아침 차에 서리가 앉았어요." },
  { w: "heatwave", m: "폭염", ex: "The heatwave lasted two weeks.", exKo: "폭염이 2주나 계속됐어요." },
  { w: "sunrise", m: "일출", ex: "We woke up early to see the sunrise.", exKo: "일출을 보려고 일찍 일어났어요." },
  { w: "sunset", m: "일몰, 노을", ex: "The sunset over the sea was beautiful.", exKo: "바다 위 노을이 아름다웠어요." },
  { w: "shade", m: "그늘", ex: "Let's rest in the shade.", exKo: "그늘에서 좀 쉬자." },
  { w: "puddle", m: "물웅덩이", ex: "The kid jumped into every puddle.", exKo: "아이가 물웅덩이마다 뛰어들었어요." },
  { w: "flood", m: "홍수", ex: "The heavy rain caused a flood.", exKo: "폭우로 홍수가 났어요." },
  { w: "drought", m: "가뭄", ex: "The drought ruined the crops.", exKo: "가뭄으로 농작물이 망가졌어요." },
  { w: "earthquake", m: "지진", ex: "A small earthquake shook the building.", exKo: "작은 지진에 건물이 흔들렸어요." },
  { w: "typhoon", m: "태풍", ex: "The typhoon is heading north.", exKo: "태풍이 북상하고 있어요." },
  { w: "pollution", m: "오염", ex: "Air pollution is serious these days.", exKo: "요즘 대기 오염이 심각해요." },
  { w: "dust", m: "먼지", ex: "The fine dust is bad today.", exKo: "오늘 미세먼지가 심해요." },
  { w: "climate", m: "기후", ex: "The climate here is mild all year.", exKo: "여기 기후는 일 년 내내 온화해요." },
  // ===== 감정 · 성격 =====
  { w: "annoyed", m: "짜증 난", ex: "I was annoyed by the constant noise.", exKo: "계속되는 소음에 짜증이 났어요." },
  { w: "frustrated", m: "답답한, 좌절한", ex: "I get frustrated when the internet is slow.", exKo: "인터넷이 느리면 답답해요." },
  { w: "jealous", m: "질투하는", ex: "He's jealous of his brother's success.", exKo: "그는 형의 성공을 질투해요." },
  { w: "grateful", m: "감사하는", ex: "I'm grateful for your help.", exKo: "도와주셔서 감사해요." },
  { w: "anxious", m: "불안한", ex: "She felt anxious before the results.", exKo: "그녀는 결과 발표 전에 불안했어요." },
  { w: "calm", m: "침착한, 차분한", ex: "Stay calm and breathe slowly.", exKo: "침착하게 천천히 숨을 쉬어." },
  { w: "cheerful", m: "쾌활한", ex: "Her cheerful voice brightens the office.", exKo: "그녀의 쾌활한 목소리가 사무실을 밝게 해요." },
  { w: "gloomy", m: "우중충한, 침울한", ex: "The gloomy weather matches my mood.", exKo: "우중충한 날씨가 내 기분 같아." },
  { w: "moody", m: "기분 변화가 심한", ex: "He gets moody when he's hungry.", exKo: "그는 배고프면 기분이 오락가락해요." },
  { w: "depressed", m: "우울한", ex: "She felt depressed after the failure.", exKo: "그녀는 실패 후 우울해했어요." },
  { w: "lonely", m: "외로운", ex: "Living alone can feel lonely sometimes.", exKo: "혼자 살면 가끔 외로워요." },
  { w: "bored", m: "지루한, 심심한", ex: "I'm bored. Let's do something fun.", exKo: "심심해. 뭔가 재밌는 거 하자." },
  { w: "curious", m: "궁금한, 호기심 많은", ex: "I'm curious about the ending.", exKo: "결말이 궁금해요." },
  { w: "confident", m: "자신감 있는", ex: "Be confident during the interview.", exKo: "면접 때 자신감 있게 해." },
  { w: "shy", m: "수줍은", ex: "She was too shy to say hello.", exKo: "그녀는 수줍어서 인사도 못 했어요." },
  { w: "outgoing", m: "외향적인", ex: "My sister is more outgoing than me.", exKo: "내 여동생이 나보다 외향적이에요." },
  { w: "generous", m: "후한, 너그러운", ex: "He's generous with his time.", exKo: "그는 시간을 아낌없이 내줘요." },
  { w: "stingy", m: "인색한", ex: "Don't be so stingy with the sauce!", exKo: "소스 좀 아끼지 마!" },
  { w: "selfish", m: "이기적인", ex: "It was selfish of me to leave early.", exKo: "먼저 가버린 건 내가 이기적이었어." },
  { w: "polite", m: "예의 바른", ex: "The staff were polite and helpful.", exKo: "직원들이 예의 바르고 친절했어요." },
  { w: "rude", m: "무례한", ex: "It's rude to interrupt people.", exKo: "말을 끊는 건 무례한 행동이에요." },
  { w: "honest", m: "정직한, 솔직한", ex: "To be honest, I didn't like it.", exKo: "솔직히 말하면 별로였어요." },
  { w: "humble", m: "겸손한", ex: "He stays humble despite his success.", exKo: "그는 성공했는데도 겸손해요." },
  { w: "arrogant", m: "거만한", ex: "His arrogant attitude annoys everyone.", exKo: "그의 거만한 태도가 모두를 짜증나게 해요." },
  { w: "stubborn", m: "고집 센", ex: "She's too stubborn to apologize first.", exKo: "그녀는 고집이 세서 먼저 사과를 안 해요." },
  { w: "patient", m: "참을성 있는; 환자", ex: "Be patient. It takes time.", exKo: "조급해하지 마. 시간이 걸려." },
  { w: "sensitive", m: "예민한, 세심한", ex: "He's sensitive about his height.", exKo: "그는 키 얘기에 예민해요." },
  { w: "sincere", m: "진심 어린", ex: "She gave me a sincere apology.", exKo: "그녀는 진심으로 사과했어요." },
  { w: "reliable", m: "믿을 수 있는", ex: "He's the most reliable person I know.", exKo: "그는 내가 아는 가장 믿음직한 사람이에요." },
  { w: "responsible", m: "책임감 있는, 담당인", ex: "Who is responsible for this project?", exKo: "이 프로젝트 담당자가 누구예요?" },
  { w: "diligent", m: "성실한", ex: "She's a diligent student.", exKo: "그녀는 성실한 학생이에요." },
  { w: "lazy", m: "게으른", ex: "I feel lazy on rainy days.", exKo: "비 오는 날엔 만사가 귀찮아요." },
  { w: "brave", m: "용감한", ex: "It was brave of you to speak up.", exKo: "네가 나서서 말한 건 용감했어." },
  { w: "careless", m: "부주의한", ex: "A careless mistake cost us the game.", exKo: "부주의한 실수로 경기를 놓쳤어요." },
  { w: "clumsy", m: "서투른, 덜렁대는", ex: "I'm too clumsy to carry that.", exKo: "난 덜렁대서 그거 못 들고 가." },
  { w: "talkative", m: "수다스러운", ex: "My uncle gets talkative after coffee.", exKo: "삼촌은 커피만 마시면 수다스러워져요." },
  { w: "strict", m: "엄격한", ex: "Our teacher is strict about deadlines.", exKo: "우리 선생님은 마감에 엄격해요." },
  { w: "gentle", m: "다정한, 부드러운", ex: "He's gentle with animals.", exKo: "그는 동물들에게 다정해요." },
  { w: "mean", m: "못된; 의미하다", ex: "Don't be mean to your little sister.", exKo: "여동생한테 못되게 굴지 마." },
  // ===== 직장 · 학교 =====
  { w: "colleague", m: "동료", ex: "I had lunch with my colleagues.", exKo: "동료들과 점심을 먹었어요." },
  { w: "boss", m: "상사", ex: "My boss approved my vacation.", exKo: "상사가 제 휴가를 승인했어요." },
  { w: "employee", m: "직원", ex: "The company has fifty employees.", exKo: "그 회사는 직원이 50명이에요." },
  { w: "employer", m: "고용주", ex: "My employer provides lunch.", exKo: "회사에서 점심을 제공해줘요." },
  { w: "staff", m: "직원들", ex: "The staff here are very friendly.", exKo: "여기 직원들이 아주 친절해요." },
  { w: "department", m: "부서", ex: "She moved to the marketing department.", exKo: "그녀는 마케팅 부서로 옮겼어요." },
  { w: "conference", m: "회의, 학회", ex: "He's attending a conference in Busan.", exKo: "그는 부산에서 열리는 콘퍼런스에 참석 중이에요." },
  { w: "presentation", m: "발표", ex: "I'm preparing a presentation for Monday.", exKo: "월요일 발표를 준비하고 있어요." },
  { w: "document", m: "문서", ex: "Please sign this document.", exKo: "이 문서에 서명해 주세요." },
  { w: "contract", m: "계약(서)", ex: "Read the contract carefully before signing.", exKo: "서명하기 전에 계약서를 꼼꼼히 읽으세요." },
  { w: "negotiate", m: "협상하다", ex: "We negotiated a better price.", exKo: "우리는 더 나은 가격으로 협상했어요." },
  { w: "promotion", m: "승진; 판촉", ex: "She got a promotion last month.", exKo: "그녀는 지난달에 승진했어요." },
  { w: "resign", m: "사직하다", ex: "He resigned after ten years.", exKo: "그는 10년 만에 회사를 그만뒀어요." },
  { w: "retire", m: "은퇴하다", ex: "My father retires next year.", exKo: "아버지는 내년에 은퇴하세요." },
  { w: "hire", m: "고용하다, 뽑다", ex: "We're hiring two new designers.", exKo: "우리는 새 디자이너 두 명을 뽑고 있어요." },
  { w: "interview", m: "면접, 인터뷰", ex: "I have a job interview tomorrow.", exKo: "내일 취업 면접이 있어요." },
  { w: "resume", m: "이력서", ex: "Update your resume regularly.", exKo: "이력서를 주기적으로 업데이트하세요." },
  { w: "career", m: "경력, 진로", ex: "She changed her career at thirty.", exKo: "그녀는 서른에 진로를 바꿨어요." },
  { w: "workload", m: "업무량", ex: "My workload doubled this month.", exKo: "이번 달 업무량이 두 배가 됐어요." },
  { w: "overtime", m: "야근, 초과 근무", ex: "I worked overtime three days in a row.", exKo: "사흘 연속 야근했어요." },
  { w: "shift", m: "교대 근무", ex: "She works the night shift.", exKo: "그녀는 야간 근무를 해요." },
  { w: "task", m: "업무, 과제", ex: "Finish this task by noon.", exKo: "이 업무를 정오까지 끝내세요." },
  { w: "duty", m: "의무, 임무", ex: "It's my duty to lock up the office.", exKo: "사무실 문단속은 제 담당이에요." },
  { w: "achievement", m: "성취, 업적", ex: "Winning that award was a huge achievement.", exKo: "그 상을 받은 건 대단한 성취였어요." },
  { w: "goal", m: "목표", ex: "My goal is to read twenty books this year.", exKo: "올해 목표는 책 20권 읽기예요." },
  { w: "effort", m: "노력", ex: "Your effort will pay off.", exKo: "네 노력은 보상받을 거야." },
  { w: "progress", m: "진전, 진행", ex: "We're making good progress.", exKo: "우리는 순조롭게 진행 중이에요." },
  { w: "feedback", m: "피드백, 의견", ex: "Could you give me feedback on this draft?", exKo: "이 초안에 피드백 좀 주실래요?" },
  { w: "attend", m: "참석하다", ex: "Will you attend the meeting tomorrow?", exKo: "내일 회의에 참석하세요?" },
  { w: "absent", m: "결석한, 결근한", ex: "He was absent from class twice.", exKo: "그는 수업에 두 번 결석했어요." },
  { w: "semester", m: "학기", ex: "The new semester starts in March.", exKo: "새 학기는 3월에 시작해요." },
  { w: "lecture", m: "강의", ex: "The lecture was surprisingly interesting.", exKo: "강의가 의외로 재미있었어요." },
  { w: "assignment", m: "과제", ex: "I stayed up finishing the assignment.", exKo: "과제를 끝내느라 밤을 새웠어요." },
  { w: "submit", m: "제출하다", ex: "Submit the report by Friday.", exKo: "금요일까지 보고서를 제출하세요." },
  { w: "grade", m: "성적; 학년", ex: "My grades improved this semester.", exKo: "이번 학기에 성적이 올랐어요." },
  { w: "scholarship", m: "장학금", ex: "She studies hard to keep her scholarship.", exKo: "그녀는 장학금을 유지하려고 열심히 공부해요." },
  { w: "tuition", m: "등록금, 수업료", ex: "Tuition goes up almost every year.", exKo: "등록금이 거의 매년 올라요." },
  { w: "major", m: "전공(하다)", ex: "What did you major in?", exKo: "전공이 뭐였어요?" },
  { w: "degree", m: "학위", ex: "He has a degree in economics.", exKo: "그는 경제학 학위가 있어요." },
  { w: "graduate", m: "졸업하다", ex: "I graduated from high school in 2020.", exKo: "저는 2020년에 고등학교를 졸업했어요." },
  { w: "memorize", m: "암기하다", ex: "I memorize ten words a day.", exKo: "하루에 단어 열 개씩 외워요." },
  { w: "concentrate", m: "집중하다", ex: "I can't concentrate with the TV on.", exKo: "TV가 켜져 있으면 집중이 안 돼요." },
  { w: "distract", m: "집중을 방해하다", ex: "My phone distracts me from studying.", exKo: "휴대폰 때문에 공부에 집중이 안 돼요." },
  { w: "review", m: "복습하다; 후기", ex: "Review your notes before the test.", exKo: "시험 전에 필기를 복습해." },
  // ===== 대화 · 관계 =====
  { w: "contact", m: "연락(하다)", ex: "Feel free to contact me anytime.", exKo: "언제든 편하게 연락 주세요." },
  { w: "reply", m: "답장(하다)", ex: "Sorry for the late reply.", exKo: "답장이 늦어서 미안해요." },
  { w: "announce", m: "발표하다, 알리다", ex: "They announced the wedding date.", exKo: "그들은 결혼 날짜를 발표했어요." },
  { w: "mention", m: "언급하다", ex: "He mentioned you at the meeting.", exKo: "그가 회의에서 네 얘기를 했어." },
  { w: "explain", m: "설명하다", ex: "Can you explain it more simply?", exKo: "좀 더 쉽게 설명해 줄래요?" },
  { w: "describe", m: "묘사하다, 설명하다", ex: "Describe the bag you lost.", exKo: "잃어버린 가방을 설명해 주세요." },
  { w: "discuss", m: "논의하다", ex: "Let's discuss this over lunch.", exKo: "점심 먹으면서 이 얘기를 하죠." },
  { w: "argue", m: "말다툼하다, 주장하다", ex: "They argued about money again.", exKo: "그들은 또 돈 문제로 다퉜어요." },
  { w: "complain", m: "불평하다", ex: "He always complains about the weather.", exKo: "그는 늘 날씨 불평을 해요." },
  { w: "apologize", m: "사과하다", ex: "I want to apologize for yesterday.", exKo: "어제 일은 사과하고 싶어요." },
  { w: "forgive", m: "용서하다", ex: "She forgave him in the end.", exKo: "그녀는 결국 그를 용서했어요." },
  { w: "admit", m: "인정하다", ex: "I admit it was my fault.", exKo: "제 잘못이었다는 걸 인정해요." },
  { w: "deny", m: "부인하다", ex: "He denied breaking the vase.", exKo: "그는 꽃병을 깬 걸 부인했어요." },
  { w: "refuse", m: "거절하다", ex: "She refused the offer politely.", exKo: "그녀는 제안을 정중히 거절했어요." },
  { w: "accept", m: "받아들이다", ex: "I accepted his apology.", exKo: "그의 사과를 받아들였어요." },
  { w: "offer", m: "제안(하다)", ex: "They offered me the job!", exKo: "그 회사에서 저한테 일자리를 제안했어요!" },
  { w: "request", m: "요청(하다)", ex: "I requested a quiet room.", exKo: "조용한 방으로 요청했어요." },
  { w: "remind", m: "상기시키다", ex: "Remind me to call mom later.", exKo: "나중에 엄마한테 전화하라고 알려줘." },
  { w: "warn", m: "경고하다", ex: "I warned you about that restaurant.", exKo: "그 식당에 대해 내가 경고했잖아." },
  { w: "encourage", m: "격려하다", ex: "My teacher encouraged me to apply.", exKo: "선생님이 지원해 보라고 격려해 주셨어요." },
  { w: "comfort", m: "위로하다", ex: "Her friends comforted her all night.", exKo: "친구들이 밤새 그녀를 위로했어요." },
  { w: "praise", m: "칭찬하다", ex: "The boss praised her presentation.", exKo: "상사가 그녀의 발표를 칭찬했어요." },
  { w: "blame", m: "탓하다", ex: "Don't blame yourself for this.", exKo: "이 일로 자책하지 마." },
  { w: "criticize", m: "비판하다", ex: "It's easy to criticize, hard to create.", exKo: "비판은 쉽고 창작은 어렵죠." },
  { w: "gossip", m: "험담, 뒷이야기", ex: "They love to gossip about celebrities.", exKo: "그들은 연예인 얘기하는 걸 좋아해요." },
  { w: "rumor", m: "소문", ex: "The rumor turned out to be false.", exKo: "그 소문은 거짓으로 드러났어요." },
  { w: "secret", m: "비밀", ex: "Can you keep a secret?", exKo: "비밀 지킬 수 있어?" },
  { w: "trust", m: "신뢰(하다)", ex: "Trust takes years to build.", exKo: "신뢰는 쌓는 데 몇 년이 걸려요." },
  { w: "doubt", m: "의심(하다)", ex: "I doubt he'll come on time.", exKo: "그가 제시간에 올지 의문이에요." },
  { w: "respect", m: "존중(하다)", ex: "We should respect different opinions.", exKo: "다른 의견을 존중해야 해요." },
  { w: "admire", m: "존경하다, 감탄하다", ex: "I admire her patience.", exKo: "그녀의 인내심이 존경스러워요." },
  { w: "appreciate", m: "감사하다", ex: "I really appreciate your support.", exKo: "지지해 주셔서 정말 감사해요." },
  { w: "misunderstand", m: "오해하다", ex: "Don't misunderstand me. I meant well.", exKo: "오해하지 마. 좋은 뜻이었어." },
  { w: "ignore", m: "무시하다", ex: "Just ignore the spam messages.", exKo: "스팸 메시지는 그냥 무시해." },
  { w: "bother", m: "귀찮게 하다", ex: "Sorry to bother you so late.", exKo: "늦은 시간에 귀찮게 해서 미안해요." },
  { w: "interrupt", m: "방해하다, 말을 끊다", ex: "Sorry to interrupt, but it's urgent.", exKo: "말씀 중에 죄송한데 급한 일이에요." },
  { w: "whisper", m: "속삭이다", ex: "She whispered the answer to me.", exKo: "그녀가 나에게 답을 속삭였어요." },
  { w: "hug", m: "포옹(하다)", ex: "She hugged her dog tightly.", exKo: "그녀는 강아지를 꼭 안았어요." },
  { w: "greet", m: "인사하다, 맞이하다", ex: "The host greeted us at the door.", exKo: "주인이 문에서 우리를 맞아줬어요." },
  { w: "introduce", m: "소개하다", ex: "Let me introduce my friend Jimin.", exKo: "제 친구 지민이를 소개할게요." },
  { w: "get along", m: "잘 지내다", ex: "I get along well with my roommate.", exKo: "룸메이트와 잘 지내요." },
  { w: "relationship", m: "관계, 사이", ex: "They have a great relationship.", exKo: "그들은 사이가 아주 좋아요." },
  // ===== 자주 쓰는 표현 =====
  { w: "pick up", m: "태우러 가다; 집어 들다", ex: "I'll pick you up at seven.", exKo: "7시에 데리러 갈게." },
  { w: "drop off", m: "내려주다", ex: "Can you drop me off at the station?", exKo: "역에 내려줄 수 있어?" },
  { w: "put off", m: "미루다", ex: "Stop putting off the dentist visit.", exKo: "치과 가는 거 그만 미뤄." },
  { w: "call off", m: "취소하다", ex: "The picnic was called off due to rain.", exKo: "비 때문에 소풍이 취소됐어요." },
  { w: "come up with", m: "생각해 내다", ex: "She came up with a brilliant idea.", exKo: "그녀가 기가 막힌 아이디어를 냈어요." },
  { w: "get over", m: "극복하다, (병이) 낫다", ex: "It took me weeks to get over the cold.", exKo: "감기가 낫는 데 몇 주 걸렸어요." },
  { w: "look after", m: "돌보다", ex: "Can you look after my cat this weekend?", exKo: "이번 주말에 내 고양이 좀 봐줄래?" },
  { w: "look up", m: "찾아보다", ex: "Look up the word in the dictionary.", exKo: "그 단어를 사전에서 찾아봐." },
  { w: "check out", m: "확인해 보다; 체크아웃", ex: "Check out this new song!", exKo: "이 신곡 한번 들어봐!" },
  { w: "bring up", m: "(화제를) 꺼내다; 기르다", ex: "Don't bring up work at dinner.", exKo: "저녁 먹을 때 일 얘기 꺼내지 마." },
  { w: "end up", m: "결국 ~하게 되다", ex: "We ended up ordering pizza again.", exKo: "결국 또 피자를 시켰어요." },
  { w: "work out", m: "운동하다; 잘 풀리다", ex: "I work out every other day.", exKo: "저는 이틀에 한 번 운동해요." },
  { w: "find out", m: "알아내다, 알게 되다", ex: "I found out the truth by accident.", exKo: "우연히 진실을 알게 됐어요." },
  { w: "point out", m: "지적하다", ex: "He pointed out a mistake in my report.", exKo: "그가 내 보고서의 실수를 지적했어요." },
  { w: "hand in", m: "제출하다", ex: "Hand in your homework by nine.", exKo: "9시까지 숙제를 제출하세요." },
  { w: "fill out", m: "작성하다", ex: "Please fill out this form.", exKo: "이 양식을 작성해 주세요." },
  { w: "throw away", m: "버리다", ex: "Don't throw away the receipt yet.", exKo: "영수증 아직 버리지 마." },
  { w: "run out of", m: "~이 다 떨어지다", ex: "We ran out of milk.", exKo: "우유가 다 떨어졌어요." },
  { w: "get rid of", m: "없애다, 처분하다", ex: "I need to get rid of these old clothes.", exKo: "이 헌 옷들을 처분해야 해요." },
  { w: "keep in touch", m: "연락하고 지내다", ex: "Let's keep in touch after graduation.", exKo: "졸업 후에도 연락하고 지내자." },
  { w: "make sure", m: "확실히 하다", ex: "Make sure the door is locked.", exKo: "문이 잠겼는지 꼭 확인해." },
  { w: "take a break", m: "잠깐 쉬다", ex: "Let's take a break for ten minutes.", exKo: "10분만 쉬자." },
  { w: "on purpose", m: "일부러", ex: "He didn't do it on purpose.", exKo: "그가 일부러 그런 건 아니야." },
  { w: "by accident", m: "실수로, 우연히", ex: "I deleted the file by accident.", exKo: "실수로 파일을 지웠어요." },
  { w: "at least", m: "적어도", ex: "Drink at least eight cups of water.", exKo: "물을 적어도 여덟 잔은 마셔." },
  { w: "in a hurry", m: "서둘러, 급히", ex: "I'm in a hurry. Can we talk later?", exKo: "지금 급해서요. 나중에 얘기해도 될까요?" },
  { w: "on my way", m: "가는 중인", ex: "I'm on my way. Ten minutes!", exKo: "가는 중이야. 10분!" },
  { w: "for a while", m: "잠시 동안, 한동안", ex: "I haven't seen him for a while.", exKo: "그를 한동안 못 봤어요." },
  { w: "as usual", m: "평소처럼", ex: "He was late as usual.", exKo: "그는 평소처럼 늦었어요." },
  { w: "right away", m: "곧바로", ex: "I'll send it right away.", exKo: "바로 보내드릴게요." },
  { w: "so far", m: "지금까지", ex: "So far, so good.", exKo: "지금까지는 순조로워요." },
  { w: "from now on", m: "이제부터", ex: "From now on, I'll exercise daily.", exKo: "이제부터 매일 운동할 거예요." },
  { w: "once in a while", m: "가끔 한 번씩", ex: "We meet once in a while for coffee.", exKo: "우리는 가끔 만나서 커피를 마셔요." },
  { w: "all of a sudden", m: "갑자기", ex: "All of a sudden, the lights went out.", exKo: "갑자기 불이 다 나갔어요." },
  { w: "no wonder", m: "어쩐지, 그럴 만하다", ex: "No wonder you're tired. You barely slept.", exKo: "어쩐지 피곤하더라. 잠을 거의 못 잤잖아." },
  { w: "worth", m: "~할 가치가 있는", ex: "The movie is worth watching twice.", exKo: "그 영화는 두 번 볼 가치가 있어요." },
  // ===== IT · 스마트폰 =====
  { w: "install", m: "설치하다", ex: "Install the app and sign up.", exKo: "앱을 설치하고 가입하세요." },
  { w: "attach", m: "첨부하다, 붙이다", ex: "I attached the file to the email.", exKo: "이메일에 파일을 첨부했어요." },
  { w: "notification", m: "알림", ex: "I turned off all notifications.", exKo: "알림을 전부 껐어요." },
  { w: "subscribe", m: "구독하다", ex: "I subscribed to the channel.", exKo: "그 채널을 구독했어요." },
  { w: "wireless", m: "무선의", ex: "These wireless earphones sound great.", exKo: "이 무선 이어폰 음질이 좋아요." },
  { w: "signal", m: "신호", ex: "There's no signal in the basement.", exKo: "지하에는 신호가 안 잡혀요." },
  { w: "storage", m: "저장 공간, 보관", ex: "My phone storage is almost full.", exKo: "폰 저장 공간이 거의 다 찼어요." },
  { w: "backup", m: "백업, 예비", ex: "Make a backup of your photos.", exKo: "사진을 백업해 두세요." },
  { w: "screenshot", m: "스크린샷", ex: "Send me a screenshot of the error.", exKo: "오류 화면 스크린샷을 보내줘." },
  { w: "mute", m: "음소거하다", ex: "I muted the group chat.", exKo: "단체 채팅방을 음소거했어요." },
  { w: "device", m: "기기, 장치", ex: "This app works on any device.", exKo: "이 앱은 어떤 기기에서든 작동해요." },
  { w: "portable", m: "휴대용의", ex: "I bought a portable fan for summer.", exKo: "여름용 휴대용 선풍기를 샀어요." },
  { w: "charge", m: "충전하다; 청구하다", ex: "My phone is charging now.", exKo: "지금 폰 충전 중이에요." },
  { w: "browse", m: "둘러보다, 검색하다", ex: "I browsed the internet all night.", exKo: "밤새 인터넷을 뒤졌어요." },
];
