// 일상 회화 단어 100개 — w: 단어, m: 뜻, ex: 예문, exKo: 예문 해석
const WORDS = [
  { w: "appointment", m: "약속, 예약", ex: "I have a dentist appointment at three.", exKo: "3시에 치과 예약이 있어요." },
  { w: "available", m: "시간이 되는, 이용 가능한", ex: "Are you available this weekend?", exKo: "이번 주말에 시간 되세요?" },
  { w: "borrow", m: "빌리다", ex: "Can I borrow your charger for a minute?", exKo: "충전기 잠깐 빌려도 될까요?" },
  { w: "recommend", m: "추천하다", ex: "What dish would you recommend here?", exKo: "여기서 어떤 요리를 추천하세요?" },
  { w: "reservation", m: "예약", ex: "I made a reservation for two people.", exKo: "두 명으로 예약했어요." },
  { w: "delicious", m: "맛있는", ex: "This soup is really delicious.", exKo: "이 수프 정말 맛있어요." },
  { w: "crowded", m: "붐비는", ex: "The subway is so crowded in the morning.", exKo: "아침에 지하철이 너무 붐벼요." },
  { w: "convenient", m: "편리한", ex: "Living near the station is very convenient.", exKo: "역 근처에 사는 건 아주 편리해요." },
  { w: "expensive", m: "비싼", ex: "That bag looks nice but too expensive.", exKo: "저 가방 예쁜데 너무 비싸요." },
  { w: "receipt", m: "영수증", ex: "Could I get a receipt, please?", exKo: "영수증 좀 주시겠어요?" },
  { w: "refund", m: "환불", ex: "I'd like to get a refund for this shirt.", exKo: "이 셔츠 환불받고 싶어요." },
  { w: "exchange", m: "교환하다", ex: "Can I exchange this for a bigger size?", exKo: "이거 더 큰 사이즈로 교환할 수 있나요?" },
  { w: "discount", m: "할인", ex: "Is there a discount for students?", exKo: "학생 할인이 있나요?" },
  { w: "directions", m: "길 안내", ex: "Could you give me directions to the museum?", exKo: "박물관 가는 길 좀 알려주시겠어요?" },
  { w: "luggage", m: "짐, 수하물", ex: "My luggage is heavier than I thought.", exKo: "제 짐이 생각보다 무겁네요." },
  { w: "departure", m: "출발", ex: "The departure time was changed to noon.", exKo: "출발 시간이 정오로 바뀌었어요." },
  { w: "arrival", m: "도착", ex: "Please check the arrival gate on the screen.", exKo: "화면에서 도착 게이트를 확인해 주세요." },
  { w: "delay", m: "지연, 미루다", ex: "The flight was delayed by two hours.", exKo: "비행기가 두 시간 지연됐어요." },
  { w: "schedule", m: "일정", ex: "My schedule is pretty tight this week.", exKo: "이번 주는 일정이 꽤 빡빡해요." },
  { w: "cancel", m: "취소하다", ex: "I need to cancel my order.", exKo: "주문을 취소해야 해요." },
  { w: "confirm", m: "확인하다", ex: "Please confirm your booking by email.", exKo: "이메일로 예약을 확인해 주세요." },
  { w: "invite", m: "초대하다", ex: "She invited me to her housewarming party.", exKo: "그녀가 집들이에 저를 초대했어요." },
  { w: "celebrate", m: "축하하다, 기념하다", ex: "Let's celebrate your new job tonight!", exKo: "오늘 밤 네 새 직장 축하하자!" },
  { w: "favor", m: "부탁", ex: "Can I ask you a favor?", exKo: "부탁 하나 해도 될까요?" },
  { w: "promise", m: "약속하다", ex: "I promise I won't be late again.", exKo: "다시는 늦지 않겠다고 약속할게요." },
  { w: "forget", m: "잊다", ex: "Don't forget to bring your umbrella.", exKo: "우산 챙기는 거 잊지 마세요." },
  { w: "remember", m: "기억하다", ex: "Do you remember where we first met?", exKo: "우리가 처음 만난 곳 기억나요?" },
  { w: "decide", m: "결정하다", ex: "I can't decide what to eat for lunch.", exKo: "점심에 뭘 먹을지 결정을 못 하겠어요." },
  { w: "suggest", m: "제안하다", ex: "He suggested taking a break.", exKo: "그가 잠깐 쉬자고 제안했어요." },
  { w: "agree", m: "동의하다", ex: "I totally agree with you.", exKo: "당신 말에 전적으로 동의해요." },
  { w: "disagree", m: "반대하다", ex: "I'm sorry, but I disagree with that idea.", exKo: "미안하지만 그 생각에는 반대예요." },
  { w: "prefer", m: "더 좋아하다", ex: "I prefer coffee to tea.", exKo: "저는 차보다 커피를 더 좋아해요." },
  { w: "prepare", m: "준비하다", ex: "I'm preparing dinner for my family.", exKo: "가족을 위해 저녁을 준비하고 있어요." },
  { w: "arrive", m: "도착하다", ex: "What time did you arrive home?", exKo: "집에 몇 시에 도착했어요?" },
  { w: "leave", m: "떠나다, 두고 오다", ex: "I left my phone in the taxi.", exKo: "택시에 휴대폰을 두고 내렸어요." },
  { w: "hurry", m: "서두르다", ex: "Hurry up, or we'll miss the bus!", exKo: "서둘러, 안 그러면 버스 놓쳐!" },
  { w: "wait", m: "기다리다", ex: "Could you wait a moment, please?", exKo: "잠시만 기다려 주시겠어요?" },
  { w: "traffic", m: "교통(량)", ex: "The traffic is terrible on Friday evenings.", exKo: "금요일 저녁엔 교통이 끔찍해요." },
  { w: "weather", m: "날씨", ex: "The weather is perfect for a picnic.", exKo: "소풍 가기에 딱 좋은 날씨예요." },
  { w: "forecast", m: "예보", ex: "The forecast says it will rain tomorrow.", exKo: "예보에서 내일 비가 온대요." },
  { w: "temperature", m: "온도, 기온", ex: "The temperature dropped a lot last night.", exKo: "어젯밤에 기온이 많이 떨어졌어요." },
  { w: "umbrella", m: "우산", ex: "Take an umbrella just in case.", exKo: "혹시 모르니 우산 챙겨 가세요." },
  { w: "laundry", m: "빨래", ex: "I need to do the laundry today.", exKo: "오늘 빨래를 해야 해요." },
  { w: "grocery", m: "식료품", ex: "Let's stop by the grocery store.", exKo: "식료품 가게에 잠깐 들르자." },
  { w: "ingredient", m: "재료", ex: "We're missing one ingredient for the recipe.", exKo: "레시피에 필요한 재료 하나가 없어요." },
  { w: "recipe", m: "요리법", ex: "This recipe is easier than it looks.", exKo: "이 요리법은 보기보다 쉬워요." },
  { w: "flavor", m: "맛, 풍미", ex: "Which flavor of ice cream do you want?", exKo: "어떤 맛 아이스크림 먹을래?" },
  { w: "spicy", m: "매운", ex: "Is this dish very spicy?", exKo: "이 요리 많이 매워요?" },
  { w: "thirsty", m: "목마른", ex: "I'm so thirsty after the run.", exKo: "달리기하고 나니 목이 너무 말라요." },
  { w: "starving", m: "몹시 배고픈", ex: "Let's eat now. I'm starving!", exKo: "지금 먹자. 배고파 죽겠어!" },
  { w: "exhausted", m: "몹시 지친", ex: "I was exhausted after work yesterday.", exKo: "어제 퇴근하고 완전히 지쳤어요." },
  { w: "comfortable", m: "편안한", ex: "This sofa is really comfortable.", exKo: "이 소파 정말 편안해요." },
  { w: "nervous", m: "긴장한", ex: "I'm nervous about the interview.", exKo: "면접 때문에 긴장돼요." },
  { w: "excited", m: "신난, 기대되는", ex: "I'm so excited about the trip!", exKo: "여행 갈 생각에 너무 신나요!" },
  { w: "disappointed", m: "실망한", ex: "I was disappointed with the movie.", exKo: "그 영화에 실망했어요." },
  { w: "embarrassed", m: "당황한, 창피한", ex: "I felt embarrassed when I fell down.", exKo: "넘어졌을 때 정말 창피했어요." },
  { w: "proud", m: "자랑스러운", ex: "I'm proud of what you did.", exKo: "네가 한 일이 자랑스러워." },
  { w: "worried", m: "걱정하는", ex: "Don't be worried. Everything will be fine.", exKo: "걱정하지 마. 다 잘될 거야." },
  { w: "relieved", m: "안도한", ex: "I was relieved to hear the good news.", exKo: "좋은 소식을 듣고 안심했어요." },
  { w: "headache", m: "두통", ex: "I have a slight headache today.", exKo: "오늘 머리가 살짝 아파요." },
  { w: "medicine", m: "약", ex: "Take this medicine after meals.", exKo: "이 약은 식후에 드세요." },
  { w: "pharmacy", m: "약국", ex: "Is there a pharmacy near here?", exKo: "이 근처에 약국이 있나요?" },
  { w: "symptom", m: "증상", ex: "What symptoms do you have?", exKo: "어떤 증상이 있으세요?" },
  { w: "recover", m: "회복하다", ex: "I hope you recover soon.", exKo: "빨리 회복하길 바라요." },
  { w: "exercise", m: "운동(하다)", ex: "I try to exercise three times a week.", exKo: "일주일에 세 번 운동하려고 해요." },
  { w: "habit", m: "습관", ex: "Going to bed early is a good habit.", exKo: "일찍 자는 건 좋은 습관이에요." },
  { w: "neighborhood", m: "동네, 이웃", ex: "There's a nice park in my neighborhood.", exKo: "우리 동네에 좋은 공원이 있어요." },
  { w: "landlord", m: "집주인", ex: "The landlord fixed the heater quickly.", exKo: "집주인이 난방기를 빨리 고쳐줬어요." },
  { w: "utility", m: "공과금, 공공요금", ex: "The rent doesn't include utility bills.", exKo: "월세에 공과금은 포함되지 않아요." },
  { w: "repair", m: "수리하다", ex: "I need to repair my bicycle brakes.", exKo: "자전거 브레이크를 수리해야 해요." },
  { w: "appliance", m: "가전제품", ex: "This store sells kitchen appliances.", exKo: "이 가게는 주방 가전을 팔아요." },
  { w: "errand", m: "심부름, 볼일", ex: "I have a few errands to run today.", exKo: "오늘 볼일이 몇 가지 있어요." },
  { w: "package", m: "소포, 택배", ex: "A package arrived for you this morning.", exKo: "오늘 아침에 네 앞으로 택배가 왔어." },
  { w: "deliver", m: "배달하다", ex: "They deliver until ten at night.", exKo: "밤 10시까지 배달해줘요." },
  { w: "order", m: "주문(하다)", ex: "Are you ready to order?", exKo: "주문하시겠어요?" },
  { w: "takeout", m: "포장 음식", ex: "Let's just get takeout tonight.", exKo: "오늘 밤엔 그냥 포장해서 먹자." },
  { w: "split", m: "나누다 (비용 등)", ex: "Let's split the bill this time.", exKo: "이번엔 계산 나눠서 하자." },
  { w: "treat", m: "한턱내다, 대접", ex: "It's my treat today. Order anything.", exKo: "오늘은 내가 살게. 아무거나 시켜." },
  { w: "hang out", m: "어울려 놀다", ex: "Do you want to hang out this Saturday?", exKo: "이번 토요일에 같이 놀래?" },
  { w: "catch up", m: "밀린 이야기를 나누다", ex: "Let's grab coffee and catch up soon.", exKo: "조만간 커피 마시면서 밀린 얘기 하자." },
  { w: "show up", m: "나타나다", ex: "He didn't show up to the meeting.", exKo: "그는 모임에 나타나지 않았어요." },
  { w: "run into", m: "우연히 만나다", ex: "I ran into an old friend at the mall.", exKo: "쇼핑몰에서 옛 친구를 우연히 만났어요." },
  { w: "look forward to", m: "기대하다", ex: "I'm looking forward to seeing you.", exKo: "만나기를 기대하고 있어요." },
  { w: "figure out", m: "알아내다, 이해하다", ex: "I can't figure out how to use this app.", exKo: "이 앱 사용법을 모르겠어요." },
  { w: "give up", m: "포기하다", ex: "Don't give up. You're almost there.", exKo: "포기하지 마. 거의 다 왔어." },
  { w: "take care of", m: "돌보다, 처리하다", ex: "I'll take care of the dishes tonight.", exKo: "오늘 설거지는 내가 할게." },
  { w: "on time", m: "제시간에", ex: "The bus rarely comes on time here.", exKo: "여기 버스는 제시간에 오는 일이 드물어요." },
  { w: "in advance", m: "미리", ex: "You should book the tickets in advance.", exKo: "표는 미리 예매하는 게 좋아요." },
  { w: "by chance", m: "우연히", ex: "Do you know his number by chance?", exKo: "혹시 그의 번호 알아요?" },
  { w: "definitely", m: "확실히, 분명히", ex: "I'll definitely be there by seven.", exKo: "7시까지 꼭 갈게요." },
  { w: "actually", m: "사실은", ex: "Actually, I've never tried sushi before.", exKo: "사실 저 초밥 한 번도 안 먹어봤어요." },
  { w: "probably", m: "아마도", ex: "It will probably rain this afternoon.", exKo: "오늘 오후에 아마 비가 올 거예요." },
  { w: "recently", m: "최근에", ex: "Have you seen any good movies recently?", exKo: "최근에 좋은 영화 본 거 있어요?" },
  { w: "suddenly", m: "갑자기", ex: "The lights suddenly went out.", exKo: "갑자기 불이 나갔어요." },
  { w: "especially", m: "특히", ex: "I love fruit, especially watermelon.", exKo: "저는 과일을 좋아하는데, 특히 수박을요." },
  { w: "opinion", m: "의견", ex: "In my opinion, this plan is better.", exKo: "제 생각에는 이 계획이 더 나아요." },
  { w: "experience", m: "경험", ex: "That trip was an amazing experience.", exKo: "그 여행은 정말 놀라운 경험이었어요." },
  { w: "opportunity", m: "기회", ex: "This is a great opportunity to learn.", exKo: "이건 배울 수 있는 좋은 기회예요." },
  { w: "mistake", m: "실수", ex: "Everyone makes mistakes sometimes.", exKo: "누구나 가끔 실수를 해요." },
  { w: "improve", m: "향상시키다", ex: "I want to improve my speaking skills.", exKo: "말하기 실력을 키우고 싶어요." },
];
